/* WordPilot v6.4.0 — A1–C2 Academy, level assessments and graded readings. */
const WP60_VERSION='6.4.0';
const WP60_PROGRESS_KEY='v6_academy_progress';
let wp60Data=null,wp60Course=activeCourse==='ru'?'ru':'en',wp60Level='A1',wp60Lesson=null,wp60QuizIndex=0,wp60QuizCorrect=0,wp60Reading=null,wp60ReadingTranslations=true;
function wp60Progress(){if(!state)return {lessons:{},tests:{},readings:{}};state.stats.taskClaims=state.stats.taskClaims||{};return state.stats.taskClaims[WP60_PROGRESS_KEY]||(state.stats.taskClaims[WP60_PROGRESS_KEY]={lessons:{},tests:{},readings:{}})}
function wp60Save(){save();if(typeof scheduleCloudSync==='function')scheduleCloudSync()}
async function wp60Load(){if(wp60Data)return wp60Data;const res=await fetch(`curriculum_v6.json?v=${VERSION}`,{cache:'no-store'});if(!res.ok)throw new Error('curriculum_v6.json');wp60Data=await res.json();return wp60Data}
function wp60Lessons(course=wp60Course,level=wp60Level){return (wp60Data?.lessons||[]).filter(x=>x.course===course&&x.level===level)}
function wp60Readings(course=wp60Course,level=wp60Level){return (wp60Data?.readings||[]).filter(x=>x.course===course&&x.level===level)}
function wp60Done(id){return !!wp60Progress().lessons?.[id]?.completed}
function wp60ReadingDone(id){return !!wp60Progress().readings?.[id]?.completed}
function wp60CourseDone(course){return (wp60Data?.lessons||[]).filter(x=>x.course===course&&wp60Done(x.id)).length}
function wp60LevelDone(course,level){return wp60Lessons(course,level).filter(x=>wp60Done(x.id)).length}
function wp60LevelMeta(level){return wp60Data?.levels?.[level]||{tr:level,desc:''}}
function wp60Reward(points,label){const old=session;session=null;adjustPoints(points);session=old;toast(`${label}: +${points} XP`)}
function wp60SetCourse(course){if(!['en','ru'].includes(course)){toast('O‘zbekçe A1–C2 kaynakları eklendiğinde Akademi açılacak.');return}wp60Course=course;wp60Lesson=null;wp60Render()}
function wp60SetLevel(level){if(!['A1','A2','B1','B2','C1','C2'].includes(level))return;wp60Level=level;wp60Lesson=null;wp60Render()}
function wp60RenderDashboard(){const box=$('#academyDashboardProgress');if(!box||!wp60Data)return;box.innerHTML=['en','ru'].map(c=>{const total=wp60Data.lessons.filter(x=>x.course===c).length,done=wp60CourseDone(c),pct=total?Math.round(done/total*100):0,meta=wp60Data.courses[c];return `<button type="button" data-nav="academy" data-academy-course="${c}"><span>${meta.flag}</span><div><b>${esc(meta.name)} Akademi</b><small>${done} / ${total} ders tamamlandı</small><progress max="100" value="${pct}"></progress></div><em>%${pct}</em></button>`}).join('')}
function wp60Render(){if(!wp60Data)return;const course=wp60Data.courses[wp60Course],lessons=wp60Lessons(),done=wp60LevelDone(wp60Course,wp60Level),allTotal=wp60Data.lessons.filter(x=>x.course===wp60Course).length,allDone=wp60CourseDone(wp60Course),meta=wp60LevelMeta(wp60Level);
  $('#academyCourseTitle').textContent=`${course.name} Akademi`;$$('[data-academy-course]').forEach(b=>b.classList.toggle('active',b.dataset.academyCourse===wp60Course));
  $('#academyLevelTabs').innerHTML=['A1','A2','B1','B2','C1','C2'].map(level=>{const d=wp60LevelDone(wp60Course,level),t=wp60Lessons(wp60Course,level).length;return `<button type="button" class="${level===wp60Level?'active':''}" data-academy-level="${level}"><b>${level}</b><small>${wp60LevelMeta(level).tr}</small><em>${d}/${t}</em></button>`}).join('');
  $('#academyOverallText').textContent=`${allDone} / ${allTotal} ders`;$('#academyOverallProgress').max=allTotal||1;$('#academyOverallProgress').value=allDone;
  $('#academyLevelEyebrow').textContent=`${wp60Level} · ${meta.tr.toUpperCase()}`;$('#academyLevelTitle').textContent=meta.desc;$('#academyLevelProgressText').textContent=`${done} / ${lessons.length} tamamlandı`;
  const score=wp60Progress().tests?.[`${wp60Course}-${wp60Level}`]?.score;$('#academyLevelSummary').innerHTML=`<span class="academy-level-badge">${wp60Level}</span><h3>${meta.tr}</h3><p>${esc(meta.desc)}</p><div><span>Ders ilerlemesi</span><b>${done}/${lessons.length}</b></div><div><span>Seviye sınavı</span><b>${Number.isFinite(score)?'%'+score:'Henüz yok'}</b></div><div><span>Okumalar</span><b>${wp60Readings().filter(x=>wp60ReadingDone(x.id)).length}/${wp60Readings().length}</b></div>`;
  $('#academyLessonGrid').innerHTML=lessons.map((lesson,i)=>{const rec=wp60Progress().lessons?.[lesson.id],completed=!!rec?.completed;return `<button type="button" class="academy-lesson-card ${completed?'completed':''}" data-academy-lesson="${lesson.id}"><span class="academy-lesson-number">${String(i+1).padStart(2,'0')}</span><div><small>${lesson.estimatedMinutes} dk · ${lesson.level}</small><b>${esc(lesson.title)}</b><p>${esc(lesson.summary)}</p></div><em>${completed?`✓ %${rec.score||100}`:'Dersi aç →'}</em></button>`}).join('');
  $('#academyLessonPanel').hidden=true;wp60RenderDashboard();
}
function wp60ShowLesson(id){const lesson=wp60Data.lessons.find(x=>x.id===id);if(!lesson)return;wp60Lesson=lesson;wp60QuizIndex=0;wp60QuizCorrect=0;const panel=$('#academyLessonPanel');panel.hidden=false;panel.innerHTML=`<div class="academy-lesson-head"><div><p class="eyebrow">${lesson.level} · DERS ${lesson.levelOrder}</p><h2>${esc(lesson.title)}</h2><p>${esc(lesson.summary)}</p><span>⏱ ${lesson.estimatedMinutes} dakika</span></div><button type="button" class="soft" data-academy-close>Kapat</button></div><div class="academy-objectives"><h3>Bu derste</h3>${lesson.objectives.map(x=>`<div><span>✓</span><p>${esc(x)}</p></div>`).join('')}</div>${lesson.sections.map(section=>`<section class="academy-content-section"><h3>${esc(section.title)}</h3>${section.body?`<p>${esc(section.body)}</p>`:''}${section.bullets?`<ul>${section.bullets.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</section>`).join('')}<section class="academy-examples"><h3>Örnekler ve ses</h3>${lesson.examples.map(ex=>`<article><button type="button" data-academy-speak="${esc(ex.target)}">🔊</button><div><b>${esc(ex.target)}</b>${ex.reading?`<small>${esc(ex.reading)}</small>`:''}<p>${esc(ex.translation)}</p></div></article>`).join('')}</section><section id="academyQuizBox" class="academy-quiz-box"></section>`;wp60RenderQuiz();panel.scrollIntoView({behavior:'smooth',block:'start'})}
function wp60RenderQuiz(){const box=$('#academyQuizBox'),lesson=wp60Lesson;if(!box||!lesson)return;if(wp60QuizIndex>=lesson.quiz.length){const score=Math.round(wp60QuizCorrect/lesson.quiz.length*100),old=wp60Progress().lessons[lesson.id];wp60Progress().lessons[lesson.id]={completed:true,score,at:Date.now()};wp60Save();if(!old?.completed)wp60Reward(35,`${lesson.level} dersi tamamlandı`);box.innerHTML=`<div class="academy-complete"><span>🎓</span><h3>Ders tamamlandı</h3><p>${lesson.quiz.length} soruda ${wp60QuizCorrect} doğru · %${score}</p><button class="primary" type="button" data-academy-next="${lesson.order+1}">Sonraki ders →</button></div>`;wp60RenderDashboard();const card=document.querySelector(`[data-academy-lesson="${lesson.id}"]`);if(card){card.classList.add('completed');card.querySelector('em').textContent=`✓ %${score}`};return}const q=lesson.quiz[wp60QuizIndex];box.innerHTML=`<div class="academy-quiz-head"><span>MİNİ TEST · ${wp60QuizIndex+1}/${lesson.quiz.length}</span><h3>${esc(q.q)}</h3></div><div class="academy-quiz-options">${q.options.map((o,i)=>`<button type="button" data-academy-answer="${i}">${esc(o)}</button>`).join('')}</div><p id="academyQuizFeedback"></p>`}
function wp60Answer(index){const q=wp60Lesson?.quiz?.[wp60QuizIndex];if(!q)return;const correct=Number(index)===Number(q.answer);$$('[data-academy-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===Number(index)&&!correct)b.classList.add('wrong')});if(correct)wp60QuizCorrect++;const f=$('#academyQuizFeedback');f.className=correct?'good':'bad';f.textContent=`${correct?'Doğru ✓':'Doğru cevap: '+q.options[q.answer]} · ${q.explanation}`;setTimeout(()=>{wp60QuizIndex++;wp60RenderQuiz()},1050)}
function wp60StartLevelTest(){const questions=wp60Lessons().flatMap(l=>l.quiz.map(q=>({...q,lesson:l.title}))).sort(()=>Math.random()-.5).slice(0,12);if(!questions.length)return;let i=0,correct=0;const panel=$('#academyLessonPanel');panel.hidden=false;function render(){if(i>=questions.length){const score=Math.round(correct/questions.length*100),key=`${wp60Course}-${wp60Level}`,old=wp60Progress().tests[key];wp60Progress().tests[key]={score,completed:true,at:Date.now()};wp60Save();if(!old?.completed)wp60Reward(score>=70?80:30,`${wp60Level} seviye sınavı`);panel.innerHTML=`<div class="academy-complete level-test-result"><span>${score>=70?'🏆':'📘'}</span><h2>${wp60Level} sınavı tamamlandı</h2><p>12 soruda ${correct} doğru · %${score}</p><b>${score>=70?'Seviye kontrolü başarılı. Bir sonraki seviyeye geçebilirsin.':'Dersleri gözden geçirip tekrar dene.'}</b><button type="button" class="primary" data-academy-test-close>Akademiye dön</button></div>`;wp60Render();panel.hidden=false;return}const q=questions[i];panel.innerHTML=`<div class="academy-lesson-head"><div><p class="eyebrow">${wp60Level} SEVİYE SINAVI</p><h2>Soru ${i+1} / ${questions.length}</h2><p>${esc(q.lesson)}</p></div><button type="button" class="soft" data-academy-test-close>Çık</button></div><div class="academy-quiz-head"><h3>${esc(q.q)}</h3></div><div class="academy-quiz-options">${q.options.map((o,n)=>`<button type="button" data-level-test-answer="${n}">${esc(o)}</button>`).join('')}</div><p id="academyQuizFeedback"></p>`;panel.scrollIntoView({behavior:'smooth',block:'start'})}panel._wp60Answer=n=>{const q=questions[i],ok=Number(n)===q.answer;if(ok)correct++;$$('[data-level-test-answer]').forEach((b,k)=>{b.disabled=true;if(k===q.answer)b.classList.add('correct');if(k===Number(n)&&!ok)b.classList.add('wrong')});const f=$('#academyQuizFeedback');f.className=ok?'good':'bad';f.textContent=ok?'Doğru ✓':`Doğru cevap: ${q.options[q.answer]}`;setTimeout(()=>{i++;render()},800)};render()}
function wp60OpenReadings(){nav('academy-readings');wp60RenderReadings()}
function wp60RenderReadings(){const readings=wp60Readings();$('#academyReadingTitle').textContent=`${wp60Data.courses[wp60Course].name} · ${wp60Level} okumaları`;$('#academyReadingList').innerHTML=`<div class="academy-reading-list-head"><b>${wp60Level} kütüphanesi</b><span>${readings.filter(x=>wp60ReadingDone(x.id)).length}/${readings.length}</span></div>`+readings.map(r=>`<button type="button" class="${wp60ReadingDone(r.id)?'completed':''}" data-academy-reading="${r.id}"><small>${r.topic} · ${r.estimatedMinutes} dk</small><b>${esc(r.title)}</b><em>${wp60ReadingDone(r.id)?'✓':'Oku →'}</em></button>`).join('');if(wp60Reading)wp60ShowReading(wp60Reading.id)}
function wp60ShowReading(id){const r=wp60Data.readings.find(x=>x.id===id);if(!r)return;wp60Reading=r;const reader=$('#academyReadingReader');reader.innerHTML=`<div class="academy-reading-head"><div><p class="eyebrow">${r.level} · ${esc(r.topic)}</p><h2>${esc(r.title)}</h2></div><div><button type="button" class="secondary" data-reading-speak-all>▶ Tamamını dinle</button><button type="button" class="soft" data-reading-toggle-tr>${wp60ReadingTranslations?'Türkçeyi gizle':'Türkçeyi göster'}</button></div></div><div class="academy-reading-lines">${r.lines.map((line,i)=>`<article><button type="button" data-academy-speak="${esc(line.text)}">🔊</button><div><b>${esc(line.text)}</b><p ${wp60ReadingTranslations?'':'hidden'}>${esc(line.translation)}</p></div></article>`).join('')}</div><div class="academy-reading-questions"><h3>Metin sonu testi</h3>${r.questions.map((q,qi)=>`<section><b>${qi+1}. ${esc(q.q)}</b><div>${q.options.map((o,oi)=>`<button type="button" data-reading-answer="${qi}:${oi}">${esc(o)}</button>`).join('')}</div></section>`).join('')}</div><button class="primary wide" type="button" data-reading-complete="${r.id}">${wp60ReadingDone(r.id)?'✓ Okuma tamamlandı':'Okumayı tamamla · +25 XP'}</button>`}
async function wp60SpeakAll(){if(!wp60Reading)return;speechSynthesis.cancel();for(const line of wp60Reading.lines){speak(line.text,COURSES[wp60Course].voice);await new Promise(r=>setTimeout(r,Math.max(1300,line.text.length*55)))} }
function wp60RenderOnCourseChange(){if(activeCourse==='en'||activeCourse==='ru')wp60Course=activeCourse;wp60RenderDashboard();if(wp510CurrentView?.()==='academy')wp60Render()}
function setupV60Events(){wp60Load().then(()=>{wp60RenderDashboard();if(wp510DashboardTab==='academy')wp510SetDashboardTab('academy',{save:false})}).catch(()=>toast('V6 Akademi içeriği yüklenemedi.'));
  const oldUpdate=updateCourseUI;updateCourseUI=function(){oldUpdate();wp60RenderOnCourseChange()};
  const oldNav=nav;nav=function(name){oldNav(name);if(name==='academy')wp60Load().then(wp60Render);if(name==='academy-readings')wp60Load().then(wp60RenderReadings)};
  document.addEventListener('click',event=>{const course=event.target.closest('[data-academy-course]');if(course){wp60SetCourse(course.dataset.academyCourse);if(event.target.closest('#academyDashboardProgress'))nav('academy');return}const level=event.target.closest('[data-academy-level]');if(level){wp60SetLevel(level.dataset.academyLevel);return}const lesson=event.target.closest('[data-academy-lesson]');if(lesson){wp60ShowLesson(lesson.dataset.academyLesson);return}const ans=event.target.closest('[data-academy-answer]');if(ans){wp60Answer(ans.dataset.academyAnswer);return}const testAns=event.target.closest('[data-level-test-answer]');if(testAns){$('#academyLessonPanel')._wp60Answer?.(testAns.dataset.levelTestAnswer);return}const next=event.target.closest('[data-academy-next]');if(next){const l=wp60Data.lessons.find(x=>x.order===Number(next.dataset.academyNext)&&x.course===wp60Course);if(l){wp60Level=l.level;wp60Render();wp60ShowLesson(l.id)}return}if(event.target.closest('[data-academy-close],[data-academy-test-close]')){$('#academyLessonPanel').hidden=true;return}if(event.target.closest('#academyLevelTestBtn')){wp60StartLevelTest();return}if(event.target.closest('#academyReadingsBtn')){wp60OpenReadings();return}const reading=event.target.closest('[data-academy-reading]');if(reading){wp60ShowReading(reading.dataset.academyReading);return}const speakBtn=event.target.closest('[data-academy-speak]');if(speakBtn){speak(speakBtn.dataset.academySpeak,COURSES[wp60Course].voice);return}if(event.target.closest('[data-reading-speak-all]')){wp60SpeakAll();return}if(event.target.closest('[data-reading-toggle-tr]')){wp60ReadingTranslations=!wp60ReadingTranslations;wp60ShowReading(wp60Reading.id);return}const ra=event.target.closest('[data-reading-answer]');if(ra){const [qi,oi]=ra.dataset.readingAnswer.split(':').map(Number),q=wp60Reading.questions[qi],ok=oi===q.answer;ra.parentElement.querySelectorAll('button').forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add('correct');if(i===oi&&!ok)b.classList.add('wrong')});return}const complete=event.target.closest('[data-reading-complete]');if(complete){const id=complete.dataset.readingComplete,old=wp60Progress().readings[id];wp60Progress().readings[id]={completed:true,at:Date.now()};wp60Save();if(!old?.completed)wp60Reward(25,'Okuma tamamlandı');wp60RenderReadings();wp60ShowReading(id);return}});
}
