/* WordPilot v6.5.0 — Flight Path learning journey, sequential lesson unlocking and roadmap. */
const WP61_VERSION='6.5.0';
const WP61_LEVELS=['A1','A2','B1','B2','C1','C2'];
const WP61_ROADMAP=[
  ['🇺🇿','O‘zbekçe Akademi','A1–C2 konu anlatımı ve özgün okumalar','yakında'],
  ['🔔','Günün kelimesi bildirimi','Kişisel çalışma saatinde hatırlatma','yakında'],
  ['⚔️','Canlı arkadaş quizi','Karşılıklı onaylı gerçek zamanlı yarışma','yakında'],
  ['🧑‍🏫','Öğretmen paneli','Öğrenci ilerleme ve haftalık raporları','yakında'],
  ['🔐','Korumalı kaynak kütüphanesi','Giriş kontrollü PDF ve çalışma dosyaları','yakında'],
  ['🗣️','Gelişmiş konuşma analizi','Kelime bazlı telaffuz ve akıcılık geri bildirimi','yakında']
];
function wp61CourseState(course){return courseStatesFor?.()[course]||state}
function wp61ProgressFor(course){const st=wp61CourseState(course);st.stats=st.stats||{};st.stats.taskClaims=st.stats.taskClaims||{};return st.stats.taskClaims[WP60_PROGRESS_KEY]||(st.stats.taskClaims[WP60_PROGRESS_KEY]={lessons:{},tests:{},readings:{}})}
function wp61LevelLessons(course,level){return (wp60Data?.lessons||[]).filter(x=>x.course===course&&x.level===level).sort((a,b)=>a.levelOrder-b.levelOrder)}
function wp61LevelComplete(course,level){const p=wp61ProgressFor(course),ls=wp61LevelLessons(course,level);return !!ls.length&&ls.every(x=>p.lessons?.[x.id]?.completed)}
function wp61LevelUnlocked(course,level){const idx=WP61_LEVELS.indexOf(level);if(idx<=0)return true;const prev=WP61_LEVELS[idx-1],p=wp61ProgressFor(course);return wp61LevelComplete(course,prev)||Number(p.tests?.[`${course}-${prev}`]?.score||0)>=70}
function wp61LessonUnlocked(course,lesson){if(!wp61LevelUnlocked(course,lesson.level))return false;const ls=wp61LevelLessons(course,lesson.level),idx=ls.findIndex(x=>x.id===lesson.id);if(idx<=0)return true;return !!wp61ProgressFor(course).lessons?.[ls[idx-1].id]?.completed}
function wp61CurrentLesson(course){const all=(wp60Data?.lessons||[]).filter(x=>x.course===course).sort((a,b)=>a.order-b.order),p=wp61ProgressFor(course);return all.find(x=>!p.lessons?.[x.id]?.completed&&wp61LessonUnlocked(course,x))||all.find(x=>!p.lessons?.[x.id]?.completed)||all.at(-1)}
function wp61TodayPoints(course){const st=wp61CourseState(course),day=typeof todayKey==='function'?todayKey():new Date().toISOString().slice(0,10);return Number(st?.stats?.days?.[day]?.points||0)}
function wp61Streak(course){return Number(wp61CourseState(course)?.stats?.streak||0)}
function wp61Week(course){const st=wp61CourseState(course),labels=['P','S','Ç','P','C','C','P'],days=[];for(let i=6;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const key=typeof dateKey==='function'?dateKey(d):d.toISOString().slice(0,10),b=st?.stats?.days?.[key]||{};days.push({label:labels[d.getDay()],done:Number(b.answers||0)>0,today:i===0})}return days}
function wp61EnsureAcademyShell(){const view=document.querySelector('#view-academy'),hero=view?.querySelector('.academy-level-hero');if(!view||!hero)return;
  if(!document.querySelector('#academyFlightStatus'))hero.insertAdjacentHTML('beforebegin',`<section id="academyFlightStatus" class="academy-flight-status panel"></section>`);
  const main=view.querySelector('.academy-main');if(main&&!main.querySelector('.academy-path-legend'))main.querySelector('.academy-main-head')?.insertAdjacentHTML('afterend',`<div class="academy-path-legend"><span><i class="done"></i>Tamamlandı</span><span><i class="current"></i>Sıradaki</span><span><i class="locked"></i>Kilitli</span></div>`);
}
function wp61RenderStatus(){const box=document.querySelector('#academyFlightStatus');if(!box||!wp60Data)return;const course=wp60Data.courses[wp60Course],lesson=wp61CurrentLesson(wp60Course),goal=Math.max(10,Number(profile?.goal||20)),points=wp61TodayPoints(wp60Course),pct=Math.min(100,Math.round(points/goal*100)),week=wp61Week(wp60Course),all=(wp60Data.lessons||[]).filter(x=>x.course===wp60Course),done=all.filter(x=>wp61ProgressFor(wp60Course).lessons?.[x.id]?.completed).length;
  box.innerHTML=`<div class="academy-flight-copy"><span class="flight-mascot">✈</span><div><p class="eyebrow">BUGÜNKÜ UÇUŞ ROTAN</p><h2>${lesson&&wp61ProgressFor(wp60Course).lessons?.[lesson.id]?.completed?'Rotayı tamamladın!':esc(lesson?.title||'Akademi yolculuğu')}</h2><p>${course.flag} ${esc(course.name)} · ${done}/${all.length} ders · ${lesson?.estimatedMinutes||5} dakikalık sonraki adım</p><button type="button" class="primary" data-v61-continue="${lesson?.id||''}">${done===all.length?'Rotayı yeniden incele':'Derse devam et'} →</button></div></div><div class="academy-flight-metrics"><div class="flight-goal-ring" style="--flight-pct:${pct*3.6}deg"><b>${points}</b><small>/${goal} XP</small></div><div class="flight-streak"><b>🔥 ${wp61Streak(wp60Course)}</b><small>günlük seri</small><div>${week.map(x=>`<span class="${x.done?'done':''} ${x.today?'today':''}">${x.label}</span>`).join('')}</div></div></div>`}
function wp61RenderPath(){const grid=document.querySelector('#academyLessonGrid');if(!grid||!wp60Data)return;const lessons=wp61LevelLessons(wp60Course,wp60Level),p=wp61ProgressFor(wp60Course),levelOpen=wp61LevelUnlocked(wp60Course,wp60Level),readings=wp60Readings(wp60Course,wp60Level),readDone=readings.filter(x=>p.readings?.[x.id]?.completed).length,test=p.tests?.[`${wp60Course}-${wp60Level}`];grid.className='academy-flight-path';
  const nodes=lessons.map((lesson,i)=>{const rec=p.lessons?.[lesson.id],done=!!rec?.completed,open=wp61LessonUnlocked(wp60Course,lesson),current=open&&!done&&(i===0||p.lessons?.[lessons[i-1]?.id]?.completed),side=i%2?'right':'left',icon=done?'✓':open?(current?'▶':String(i+1)):'🔒';return `<button type="button" class="flight-node ${side} ${done?'completed':current?'current':open?'open':'locked'}" data-academy-lesson="${lesson.id}" ${open?'':'disabled'}><span class="flight-node-orbit"><i>${icon}</i></span><div><small>${lesson.level} · ${lesson.estimatedMinutes} DK</small><b>${esc(lesson.title)}</b><p>${esc(lesson.summary)}</p><em>${done?`Tamamlandı · %${rec.score||100}`:current?'Sıradaki ders':open?'Açık':'Önceki dersi tamamla'}</em></div></button>`}).join('');
  const lockedNote=!levelOpen?`<div class="flight-level-lock"><span>🔒</span><div><b>${wp60Level} rotası henüz kilitli</b><p>${WP61_LEVELS[Math.max(0,WP61_LEVELS.indexOf(wp60Level)-1)]} derslerini tamamla veya seviye sınavından en az %70 al.</p></div></div>`:'';
  grid.innerHTML=`${lockedNote}<div class="flight-airport start"><span>🛫</span><b>${wp60Level} kalkış noktası</b></div>${nodes}<button type="button" class="flight-special reading" data-v61-readings><span>📚</span><div><b>Okuma durağı</b><small>${readDone}/${readings.length} metin tamamlandı</small></div></button><button type="button" class="flight-special checkpoint ${test?.score>=70?'completed':''}" data-v61-test><span>${test?.score>=70?'🏆':'🛂'}</span><div><b>${wp60Level} kontrol noktası</b><small>${Number.isFinite(test?.score)?`Son puan: %${test.score}`:'12 soruluk seviye sınavı'}</small></div></button><div class="flight-airport finish"><span>${test?.score>=70?'🛬':'🏁'}</span><b>${test?.score>=70?`${wp60Level} rotası tamamlandı`:'Rotayı tamamla ve sıradaki seviyeyi aç'}</b></div>`}
function wp61RenderRoadmap(){const root=document.querySelector('[data-dashboard-panel="academy"]');if(!root)return;let box=document.querySelector('#wp61Roadmap');if(!box){root.insertAdjacentHTML('beforeend',`<section id="wp61Roadmap" class="wp61-roadmap"><div class="wp61-roadmap-head"><div><p class="eyebrow">WORDPILOT YOL HARİTASI</p><h3>Sıradaki geliştirmeler</h3></div><span>V6+ · planlandı</span></div><div class="wp61-roadmap-grid"></div></section>`);box=document.querySelector('#wp61Roadmap')}
  box.querySelector('.wp61-roadmap-grid').innerHTML=WP61_ROADMAP.map(x=>`<article><span>${x[0]}</span><div><b>${x[1]}</b><p>${x[2]}</p></div><em>${x[3]}</em></article>`).join('')}
function wp61RenderAcademyProgressCards(){const box=document.querySelector('#academyDashboardProgress');if(!box||!wp60Data)return;box.innerHTML=['en','ru'].map(c=>{const all=wp60Data.lessons.filter(x=>x.course===c),p=wp61ProgressFor(c),done=all.filter(x=>p.lessons?.[x.id]?.completed).length,pct=all.length?Math.round(done/all.length*100):0,meta=wp60Data.courses[c],next=wp61CurrentLesson(c);return `<button type="button" data-nav="academy" data-academy-course="${c}"><span>${meta.flag}</span><div><b>${esc(meta.name)} Akademi</b><small>${done} / ${all.length} ders · sıradaki: ${esc(next?.title||'tamamlandı')}</small><progress max="100" value="${pct}"></progress></div><em>%${pct}</em></button>`}).join('')}
function wp61RenderDashboardContinue(){const root=document.querySelector('[data-dashboard-panel="academy"]'),hero=root?.querySelector('.academy-dashboard-hero');if(!hero||!wp60Data)return;let card=root.querySelector('#wp61DashboardContinue');if(!card){hero.insertAdjacentHTML('afterend','<div id="wp61DashboardContinue" class="wp61-dashboard-continue"></div>');card=root.querySelector('#wp61DashboardContinue')}
  const course=activeCourse==='ru'?'ru':'en',lesson=wp61CurrentLesson(course),p=wp61ProgressFor(course),all=wp60Data.lessons.filter(x=>x.course===course),done=all.filter(x=>p.lessons?.[x.id]?.completed).length,pct=Math.round(done/(all.length||1)*100);card.innerHTML=`<button type="button" data-v61-dashboard-continue="${lesson?.id||''}" data-v61-course="${course}"><span>${wp60Data.courses[course].flag}</span><div><small>KALDIĞIN YERDEN DEVAM ET</small><b>${esc(lesson?.title||'Akademi rotası')}</b><progress max="100" value="${pct}"></progress><em>${done}/${all.length} ders · %${pct}</em></div><strong>→</strong></button>`}
function wp61EnhanceAcademy(){wp61EnsureAcademyShell();wp61RenderStatus();wp61RenderPath()}
function wp61Celebrate(text='Rota tamamlandı!'){let layer=document.querySelector('#wp61Celebration');if(layer)layer.remove();layer=document.createElement('div');layer.id='wp61Celebration';layer.className='wp61-celebration';layer.innerHTML=`<div><span>✈️</span><b>${esc(text)}</b><small>Yeni bir adım daha tamamlandı.</small></div>${Array.from({length:18},(_,i)=>`<i style="--i:${i}"></i>`).join('')}`;document.body.appendChild(layer);setTimeout(()=>layer.classList.add('show'),10);setTimeout(()=>layer.remove(),1900)}
function setupV61Events(){wp61EnsureAcademyShell();
  const oldSetCourse=wp60SetCourse;wp60SetCourse=async function(course){if(!['en','ru'].includes(course)){oldSetCourse(course);return}if(course!==activeCourse)await switchCourse(course);wp60Course=course;wp60Lesson=null;nav('academy');wp60Render()};
  const oldRender=wp60Render;wp60Render=function(){oldRender();wp61EnhanceAcademy()};
  const oldDash=wp60RenderDashboard;wp60RenderDashboard=function(){oldDash();wp61RenderAcademyProgressCards();wp61RenderDashboardContinue();wp61RenderRoadmap()};
  const oldAnswer=wp60Answer;wp60Answer=function(index){const before=wp60QuizIndex,len=wp60Lesson?.quiz?.length||0;oldAnswer(index);if(before===len-1)setTimeout(()=>{wp61Celebrate(`${wp60Lesson?.level||''} dersi tamamlandı`);wp61RenderPath();wp61RenderStatus();wp61RenderAcademyProgressCards();wp61RenderDashboardContinue()},1200)};
  document.addEventListener('click',e=>{const c=e.target.closest('[data-v61-continue]');if(c){const id=c.dataset.v61Continue;if(id){const l=wp60Data?.lessons?.find(x=>x.id===id);if(l){wp60Level=l.level;wp60Render();wp60ShowLesson(id)}}return}const d=e.target.closest('[data-v61-dashboard-continue]');if(d){const course=d.dataset.v61Course;wp60SetCourse(course).then(()=>{const l=wp60Data?.lessons?.find(x=>x.id===d.dataset.v61DashboardContinue);if(l){wp60Level=l.level;wp60Render();wp60ShowLesson(l.id)}});return}if(e.target.closest('[data-v61-readings]')){wp60OpenReadings();return}if(e.target.closest('[data-v61-test]')){wp60StartLevelTest();return}});
  wp60Load().then(()=>{wp61EnhanceAcademy();wp61RenderAcademyProgressCards();wp61RenderDashboardContinue();wp61RenderRoadmap()});
}
