/* WordPilot v7.0.0 — source-driven content expansion, Verb Lab and Vocabulary Atlas. */
const WP63_VERSION='7.0.0';
let wp63Verbs=null,wp63Atlas=null,wp63Exam=null,wp63VerbLevel='all',wp63VerbQuery='',wp63VocabTopic='all',wp63VocabQuery='';
async function wp63Load(){
  if(!wp63Verbs){const r=await fetch(`ru_verb_lab.json?v=${VERSION}`,{cache:'no-store'});if(!r.ok)throw new Error('ru_verb_lab.json');wp63Verbs=await r.json()}
  if(!wp63Atlas){const r=await fetch(`source_atlas_v63.json?v=${VERSION}`,{cache:'no-store'});if(!r.ok)throw new Error('source_atlas_v63.json');wp63Atlas=await r.json()}
  if(!wp63Exam){const r=await fetch(`ru_exam_lab.json?v=${VERSION}`,{cache:'no-store'});if(!r.ok)throw new Error('ru_exam_lab.json');wp63Exam=await r.json()}
  return {verbs:wp63Verbs,atlas:wp63Atlas,exam:wp63Exam};
}
function wp63Progress(){state.stats.taskClaims=state.stats.taskClaims||{};const row=state.stats.taskClaims.v63_content||(state.stats.taskClaims.v63_content={verbs:{},topics:{},exams:{}});row.verbs=row.verbs||{};row.topics=row.topics||{};row.exams=row.exams||{};return row}
function wp63Save(){save();if(typeof scheduleCloudSync==='function')scheduleCloudSync()}
function wp63EnsureViews(){if(document.querySelector('#view-verb-lab'))return;const anchor=document.querySelector('#view-academy-readings');if(!anchor)return;
 anchor.insertAdjacentHTML('afterend',`<section id="view-verb-lab" class="view academy-view"><div class="section-title"><div><p class="eyebrow">RUSÇA FİİL LABORATUVARI</p><h1>Görünüş, hareket ve yönetim</h1><p class="muted">Kaynak fiil korpusunun konu yapısıyla hazırlanmış özgün modeller.</p></div><button class="secondary" type="button" data-nav="academy">← Akademi</button></div><section class="wp63-lab-toolbar panel"><div id="wp63VerbLevels" class="wp63-filter-tabs"></div><label>Fiil ara<input id="wp63VerbSearch" type="search" placeholder="örn. читать, yardım etmek"></label></section><div class="wp63-lab-layout"><aside id="wp63VerbList" class="panel wp63-lab-list"></aside><article id="wp63VerbDetail" class="panel wp63-lab-detail"><div class="story-empty"><span>⚙️</span><h2>Bir fiil modeli seç</h2><p>Görünüş çiftini, yönetimi ve örneği birlikte incele.</p></div></article></div></section>
 <section id="view-vocab-atlas" class="view academy-view"><div class="section-title"><div><p class="eyebrow">RUSÇA KELİME ATLASI</p><h1>Temaya göre bağlamlı kelime</h1><p class="muted">1300 kontrollü kayıt ve V6.3 ifadeleri tek tematik laboratuvarda.</p></div><button class="secondary" type="button" data-nav="academy">← Akademi</button></div><section class="wp63-lab-toolbar panel"><label>Tema<select id="wp63VocabTopic"></select></label><label>Kelime veya anlam ara<input id="wp63VocabSearch" type="search" placeholder="Rusça veya Türkçe"></label></section><div id="wp63VocabStats" class="wp63-vocab-stats"></div><div id="wp63VocabGrid" class="wp63-vocab-grid"></div></section>
 <section id="view-source-atlas" class="view academy-view"><div class="section-title"><div><p class="eyebrow">V6.3 KAYNAK ATLASI</p><h1>Yüklenen arşivlerden üretilen yapı</h1><p class="muted">Telifli metinler siteye kopyalanmadı; öğretim yapıları özgün WordPilot içeriğine dönüştürüldü.</p></div><button class="secondary" type="button" data-nav="academy">← Akademi</button></div><div id="wp63SourceSummary" class="wp63-source-summary panel"></div><div id="wp63SourceGrid" class="wp63-source-grid"></div></section>
 <section id="view-cert-lab" class="view academy-view"><div class="section-title"><div><p class="eyebrow">RUSÇA SERTİFİKA LABORATUVARI</p><h1>A1–C2 beceri görevleri</h1><p class="muted">Gramer, kelime, okuma, iletişim, dönüştürme ve yazma için 36 özgün görev.</p></div><button class="secondary" type="button" data-nav="academy">← Akademi</button></div><section class="wp63-lab-toolbar panel"><label>Seviye<select id="wp63ExamLevel"><option value="all">Tüm seviyeler</option><option>A1</option><option>A2</option><option>B1</option><option>B2</option><option>C1</option><option>C2</option></select></label><label>Beceri<select id="wp63ExamSkill"><option value="all">Tüm beceriler</option><option value="lexicon">Kelime</option><option value="grammar">Gramer</option><option value="reading">Okuma</option><option value="function">İletişim</option><option value="transformation">Dönüştürme</option><option value="writing">Yazma</option></select></label></section><div class="wp63-lab-layout"><aside id="wp63ExamList" class="panel wp63-lab-list"></aside><article id="wp63ExamDetail" class="panel wp63-lab-detail"><div class="story-empty"><span>✅</span><h2>Bir sertifika görevi seç</h2><p>Cevabını kontrol et ve ilerlemene kaydet.</p></div></article></div></section>`)}
function wp63InjectAcademy(){const hero=document.querySelector('.academy-level-hero');if(!hero||document.querySelector('#wp63ResourceStrip'))return;hero.insertAdjacentHTML('afterend',`<section id="wp63ResourceStrip" class="wp63-resource-strip"><button type="button" data-nav="verb-lab"><span>⚙️</span><div><b>Fiil Laboratuvarı</b><small>36 görünüş ve hareket modeli</small></div><em>Yeni</em></button><button type="button" data-nav="vocab-atlas"><span>🧠</span><div><b>Kelime Atlası</b><small>Tematik Rusça içerik</small></div><em>1120</em></button><button type="button" data-nav="academy-readings"><span>📚</span><div><b>Okuma Kütüphanesi</b><small>48 A1–C2 akademi okuması</small></div><em>A1–C2</em></button><button type="button" data-nav="cert-lab"><span>✅</span><div><b>Sertifika Laboratuvarı</b><small>36 özgün A1–C2 görev</small></div><em>Yeni</em></button><button type="button" data-nav="source-atlas"><span>🗂️</span><div><b>Kaynak Atlası</b><small>165 dosyanın öğretim çıktısı</small></div><em>V6.3</em></button></section>`)}
function wp63UpdateHero(){const hero=document.querySelector('.academy-dashboard-hero');if(!hero||!wp60Data)return;const badges=hero.querySelector('.academy-dashboard-badges');if(badges)badges.innerHTML=`<span>${wp60Data.lessons.length} kapsamlı ders</span><span>${wp60Data.readings.length} derecelendirilmiş okuma</span><span>36 fiil modeli</span><span>36 sertifika görevi</span><span>${COURSES.ru.displayCount} Rusça kayıt</span>`;const p=hero.querySelector('p:not(.eyebrow)');if(p)p.textContent='Yüklenen gramer, kelime, fiil, test ve okuma kaynaklarının yapısından üretilmiş özgün A1–C2 Akademi, atölyeler ve laboratuvarlar.'}
function wp63VerbRows(){return (wp63Verbs||[]).filter(v=>(wp63VerbLevel==='all'||v.level===wp63VerbLevel)&&(!wp63VerbQuery||`${v.imperfective} ${v.perfective} ${v.translation}`.toLocaleLowerCase('tr').includes(wp63VerbQuery.toLocaleLowerCase('tr'))))}
function wp63RenderVerbList(){if(!wp63Verbs)return;const levels=['all','A1','A2','B1','B2','C1'];document.querySelector('#wp63VerbLevels').innerHTML=levels.map(x=>`<button type="button" class="${wp63VerbLevel===x?'active':''}" data-wp63-verb-level="${x}">${x==='all'?'Tümü':x}</button>`).join('');const rows=wp63VerbRows(),done=wp63Progress().verbs;document.querySelector('#wp63VerbList').innerHTML=`<div class="wp63-list-head"><b>${rows.length} model</b><small>${Object.keys(done).length} çalışıldı</small></div>${rows.map(v=>`<button type="button" class="${done[v.id]?'done':''}" data-wp63-verb="${v.id}"><span>${v.level}</span><div><b>${esc(v.imperfective)}${v.perfective&&v.perfective!=='—'?` ↔ ${esc(v.perfective)}`:''}</b><small>${esc(v.translation)}</small></div><em>${done[v.id]?'✓':'→'}</em></button>`).join('')||'<p class="muted">Aramana uygun fiil yok.</p>'}`}
function wp63ShowVerb(id){const v=wp63Verbs?.find(x=>x.id===id),box=document.querySelector('#wp63VerbDetail');if(!v||!box)return;box.innerHTML=`<div class="wp63-verb-head"><span>${v.level}</span><div><p class="eyebrow">GÖRÜNÜŞ / KULLANIM</p><h2>${esc(v.imperfective)}${v.perfective!=='—'?` ↔ ${esc(v.perfective)}`:''}</h2><p>${esc(v.translation)}</p></div><button type="button" data-wp63-speak="${esc(v.imperfective)}">🔊</button></div><dl class="wp63-verb-meta"><div><dt>Vurgu</dt><dd>${esc(v.stress)}</dd></div><div><dt>Okunuş</dt><dd>${esc(v.reading)}</dd></div><div><dt>Yönetim</dt><dd>${esc(v.government)}</dd></div><div><dt>Görünüş notu</dt><dd>${esc(v.note)}</dd></div></dl><section class="wp63-example"><button type="button" data-wp63-speak="${esc(v.example)}">🔊</button><div><b>${esc(v.example)}</b><p>${esc(v.example_translation)}</p></div></section><button type="button" class="primary wide" data-wp63-verb-done="${v.id}">${wp63Progress().verbs[v.id]?'Çalışıldı ✓':'Bu modeli çalıştım · +15 XP'}</button>`}
async function wp63RenderVocab(){if(activeCourse!=='ru')await switchCourse('ru');const all=courseWordCache.ru||words,topics=[...new Set(all.map(x=>x.topic).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'));const select=document.querySelector('#wp63VocabTopic');select.innerHTML=`<option value="all">Tüm temalar</option>${topics.map(t=>`<option ${t===wp63VocabTopic?'selected':''}>${esc(t)}</option>`).join('')}`;const q=wp63VocabQuery.toLocaleLowerCase('tr'),rows=all.filter(x=>(wp63VocabTopic==='all'||x.topic===wp63VocabTopic)&&(!q||`${x.word} ${x.stress} ${x.translation} ${x.reading}`.toLocaleLowerCase('tr').includes(q))).slice(0,240);document.querySelector('#wp63VocabStats').innerHTML=`<article><b>${all.length}</b><small>toplam Rusça kayıt</small></article><article><b>${topics.length}</b><small>tema</small></article><article><b>${all.filter(x=>x.sourcePack==='v63').length}</b><small>V6.3 yeni ifade</small></article>`;document.querySelector('#wp63VocabGrid').innerHTML=rows.map(x=>`<article><div><span>${esc(x.level||'A1')}</span><small>${esc(x.topic||'')}</small></div><h3>${esc(x.stress||x.word)}</h3><p class="reading">${esc(x.reading||'')}</p><b>${esc(x.translation||x.meaning||'')}</b><p>${esc(x.example||'')}</p><footer><button type="button" data-wp63-speak="${esc(x.word)}">🔊 Dinle</button><button type="button" data-info="${x.id}">Detay →</button></footer></article>`).join('')||'<p class="muted">Bu filtrede kayıt yok.</p>'}
function wp63RenderSource(){if(!wp63Atlas)return;const s=document.querySelector('#wp63SourceSummary'),g=document.querySelector('#wp63SourceGrid');s.innerHTML=`<div><span>🎓</span><div><p class="eyebrow">V6.3 İÇERİK ÇIKTISI</p><h2>${wp63Atlas.counts.sourceFiles} kaynak dosyası → ${wp63Atlas.counts.lessons} ders · ${wp63Atlas.counts.readings} okuma · ${wp63Atlas.counts.russianWords} Rusça kayıt</h2><p>${esc(wp63Atlas.policy)}</p></div></div>`;g.innerHTML=wp63Atlas.packs.map(p=>`<article><span>${p.icon}</span><div><small>${p.files} kaynak dosyası</small><h3>${esc(p.title)}</h3><p>${p.focus.map(x=>`<em>${esc(x)}</em>`).join('')}</p><b>${esc(p.output)}</b></div></article>`).join('')}
let wp63ExamLevel='all',wp63ExamSkill='all',wp63ExamActive='';
function wp63ExamRows(){return (wp63Exam?.tasks||[]).filter(x=>(wp63ExamLevel==='all'||x.level===wp63ExamLevel)&&(wp63ExamSkill==='all'||x.skill===wp63ExamSkill))}
function wp63RenderExamList(){const rows=wp63ExamRows(),done=wp63Progress().exams,box=document.querySelector('#wp63ExamList');if(!box)return;box.innerHTML=`<div class="wp63-list-head"><b>${rows.length} görev</b><small>${Object.keys(done).length} tamamlandı</small></div>${rows.map(x=>`<button type="button" class="${done[x.id]?'done':''} ${wp63ExamActive===x.id?'active':''}" data-wp63-exam="${x.id}"><span>${x.level}</span><div><b>${esc(x.title)}</b><small>${esc(x.skillLabel)} · ${x.estimatedMinutes} dk</small></div><em>${done[x.id]?'✓':'→'}</em></button>`).join('')||'<p class="muted">Bu filtrede görev yok.</p>'}`}
function wp63ShowExam(id){const x=wp63Exam?.tasks?.find(t=>t.id===id),box=document.querySelector('#wp63ExamDetail');if(!x||!box)return;wp63ExamActive=id;wp63RenderExamList();box.innerHTML=`<div class="wp63-exam-head"><span>${x.level}</span><div><p class="eyebrow">${esc(x.skillLabel).toUpperCase()}</p><h2>${esc(x.title)}</h2><small>Yaklaşık ${x.estimatedMinutes} dakika</small></div></div><section class="wp63-exam-prompt"><p>${esc(x.prompt)}</p></section>${x.type==='choice'?`<div class="wp63-exam-options">${x.options.map(o=>`<button type="button" data-wp63-exam-option="${esc(o)}">${esc(o)}</button>`).join('')}</div>`:`<label class="wp63-writing-box">Cevabın<textarea id="wp63ExamWriting" rows="7" placeholder="Cevabını burada taslak olarak yaz…"></textarea></label><button class="secondary wide" type="button" data-wp63-exam-reveal>Örnek cevabı göster</button>`}<div id="wp63ExamFeedback" class="wp63-exam-feedback" hidden></div>`}
function wp63CompleteExam(x,ok=true){const done=wp63Progress().exams;if(!done[x.id]&&ok){done[x.id]={at:Date.now(),level:x.level,skill:x.skill};const old=session;session=null;adjustPoints(20);session=old;wp63Save();toast('Sertifika görevi tamamlandı: +20 XP')}wp63RenderExamList()}
function wp63CheckExam(answer){const x=wp63Exam?.tasks?.find(t=>t.id===wp63ExamActive),f=document.querySelector('#wp63ExamFeedback');if(!x||!f)return;const ok=answer===x.answer;f.hidden=false;f.className=`wp63-exam-feedback ${ok?'ok':'bad'}`;f.innerHTML=`<b>${ok?'Doğru ✓':'Tekrar düşün'}</b><p>${esc(x.explanation)}</p>${!ok?`<small>Doğru cevap: ${esc(x.answer)}</small>`:''}`;document.querySelectorAll('[data-wp63-exam-option]').forEach(b=>{b.disabled=true;if(b.dataset.wp63ExamOption===x.answer)b.classList.add('correct');else if(b.dataset.wp63ExamOption===answer)b.classList.add('wrong')});if(ok)wp63CompleteExam(x,true)}
function wp63RevealExam(){const x=wp63Exam?.tasks?.find(t=>t.id===wp63ExamActive),f=document.querySelector('#wp63ExamFeedback');if(!x||!f)return;f.hidden=false;f.className='wp63-exam-feedback model';f.innerHTML=`<b>Örnek / ölçüt</b><p>${esc(x.answer)}</p><small>${esc(x.explanation)}</small><button class="primary wide" type="button" data-wp63-exam-selfdone>Çalışmayı tamamladım · +20 XP</button>`}
function wp63EnhanceLesson(){const p=document.querySelector('#academyLessonPanel');if(!p||!wp60Lesson?.practice?.length||p.querySelector('.wp63-practice'))return;p.querySelector('#academyQuizBox')?.insertAdjacentHTML('beforebegin',`<section class="wp63-practice"><p class="eyebrow">KAYNAK ATÖLYESİ</p><h3>Kontrollü üretim</h3>${wp60Lesson.practice.map((x,i)=>`<details><summary>${i+1}. ${esc(x.prompt)}</summary>${x.hint?`<p>İpucu: ${esc(x.hint)}</p>`:''}<b>${esc(x.answer)}</b></details>`).join('')}</section>`)}
function wp63UpdateRoadmap(){if(!Array.isArray(WP61_ROADMAP))return;WP61_ROADMAP.splice(0,WP61_ROADMAP.length,['📚','Kaynak tabanlı içerik genişlemesi','102 ders, 48 akademi okuması ve fiil laboratuvarı','aktif'],['🧠','SM-2 akıllı tekrar','Cevap kalitesine göre kişisel tekrar tarihleri','aktif'],['🏆','Dil sekmeli lig','English, Русский ve O‘zbekcha ligleri','aktif'],['🛡️','Sunucu doğrulamalı XP','Soru bileti, hız ve tekrar denetimi','sırada'],['🤝','Güvenli arkadaşlık','Karşılıklı onay, reddetme ve engelleme','yakında'],['🇺🇿','O‘zbekçe Akademi','Kaynak paketi eklendiğinde A1–C2','yakında'])}
function setupV63Events(){wp63UpdateRoadmap();
 const oldNav=nav;nav=function(name){const r=oldNav(name);if(name==='verb-lab')wp63Load().then(()=>{wp63RenderVerbList();const first=wp63VerbRows()[0];if(first)wp63ShowVerb(first.id)});if(name==='vocab-atlas')wp63RenderVocab();if(name==='source-atlas')wp63Load().then(wp63RenderSource);if(name==='cert-lab')wp63Load().then(()=>{wp63RenderExamList();const first=wp63ExamRows()[0];if(first)wp63ShowExam(first.id)});return r};
 const oldShow=wp60ShowLesson;wp60ShowLesson=function(id){oldShow(id);setTimeout(wp63EnhanceLesson,0)};
 const oldDash=wp60RenderDashboard;wp60RenderDashboard=function(){oldDash();wp63UpdateHero()};
 document.addEventListener('click',e=>{const l=e.target.closest('[data-wp63-verb-level]');if(l){wp63VerbLevel=l.dataset.wp63VerbLevel;wp63RenderVerbList();return}const v=e.target.closest('[data-wp63-verb]');if(v){wp63ShowVerb(v.dataset.wp63Verb);return}const done=e.target.closest('[data-wp63-verb-done]');if(done){const id=done.dataset.wp63VerbDone;if(!wp63Progress().verbs[id]){wp63Progress().verbs[id]={at:Date.now()};const old=session;session=null;adjustPoints(15);session=old;wp63Save();toast('Fiil modeli tamamlandı: +15 XP')}wp63RenderVerbList();wp63ShowVerb(id);return}const ex=e.target.closest('[data-wp63-exam]');if(ex){wp63ShowExam(ex.dataset.wp63Exam);return}const opt=e.target.closest('[data-wp63-exam-option]');if(opt){wp63CheckExam(opt.dataset.wp63ExamOption);return}if(e.target.closest('[data-wp63-exam-reveal]')){wp63RevealExam();return}if(e.target.closest('[data-wp63-exam-selfdone]')){const x=wp63Exam?.tasks?.find(t=>t.id===wp63ExamActive);if(x)wp63CompleteExam(x,true);return}const sp=e.target.closest('[data-wp63-speak]');if(sp){speak(sp.dataset.wp63Speak,'ru-RU');return}});
 document.addEventListener('input',e=>{if(e.target.id==='wp63VerbSearch'){wp63VerbQuery=e.target.value;wp63RenderVerbList()}if(e.target.id==='wp63VocabSearch'){wp63VocabQuery=e.target.value;wp63RenderVocab()}});document.addEventListener('change',e=>{if(e.target.id==='wp63VocabTopic'){wp63VocabTopic=e.target.value;wp63RenderVocab()}if(e.target.id==='wp63ExamLevel'){wp63ExamLevel=e.target.value;wp63ExamActive='';wp63RenderExamList()}if(e.target.id==='wp63ExamSkill'){wp63ExamSkill=e.target.value;wp63ExamActive='';wp63RenderExamList()}});
}

function wp63AfterInit(){
  if(!state)return;
  wp63EnsureViews();
  wp63InjectAcademy();
  wp63Load().then(()=>{
    wp63UpdateHero();
    wp63RenderSource();
    wp63RenderVerbList();
    wp63InjectAcademy();
  }).catch(error=>{console.error('V6.3 kaynak laboratuvarı yüklenemedi',error);toast('V6.3 kaynak laboratuvarı yüklenemedi.')});
}
