/* WordPilot v7.1.2 — language routing fix, complete flags, translated learning hub and feedback channel. */
const WP712_VERSION='8.0.0';
const WP712_TEXT={
 en:{ideas:'Ideas & updates',ideasShort:'Ideas',feedbackTitle:'Help shape WordPilot',feedbackDesc:'Share a feature idea, report a problem or suggest new learning content.',category:'Category',subject:'Short title',message:'Your suggestion',messagePh:'Describe what you would like to improve…',send:'Send suggestion',close:'Close',privacy:'Please do not include passwords, payment information or sensitive personal data.',login:'Sign in with Google to send this suggestion securely.',sent:'Thank you. Your suggestion was sent.',saved:'Your draft was saved on this device.',error:'The suggestion could not be sent. Please try again.',idea:'New feature',bug:'Problem / bug',content:'Learning content',conversation:'Conversation Coach',other:'Other',hubAria:'Learning areas',hubSummary:{academy:'Follow a structured A1–C2 learning route.',games:'Choose vocabulary, listening, writing or sentence practice.',stories:'Read level-based original stories and review words in context.',speak:'Practise pronunciation and speak with Conversation Coach.',collections:'Open smart reviews and your personal word lists.',progress:'View course PP, accuracy, reviews and league progress.'},gamesEye:'PRACTICE CENTRE',gamesTitle:'Choose a practice mode',speakEye:'LISTEN & SPEAK',speakTitle:'Voice and conversation centre',speakDesc:'Listening, pronunciation and secure AI speaking practice in your active course.',storiesEye:'READ & REINFORCE',storiesTitle:'Stories and personal plan',storiesDesc:'Learn in context and prioritise reviews automatically.',collectionsEye:'WORD COLLECTIONS',collectionsTitle:'Study with prepared lists',progressEye:'COURSE PROGRESS',progressTitle:'PP, league and development analysis',progressDesc:'Each target language keeps its own progress.',scoreEye:'LANGUAGE-BASED SCORING',scoreTitle:'Each course has a separate score',scoreNote:'Global PP is combined only for the league'},
 tr:{ideas:'Öneri & Yenilik',ideasShort:'Öneri',feedbackTitle:'WordPilot’u birlikte geliştirelim',feedbackDesc:'Yeni özellik öner, bir hatayı bildir veya öğrenme içeriği talep et.',category:'Kategori',subject:'Kısa başlık',message:'Önerin',messagePh:'Neyi geliştirmemizi istediğini ayrıntılı yaz…',send:'Öneriyi gönder',close:'Kapat',privacy:'Şifre, ödeme bilgisi veya hassas kişisel veri yazma.',login:'Öneriyi güvenli göndermek için Google hesabınla giriş yap.',sent:'Teşekkürler. Önerin gönderildi.',saved:'Taslağın bu cihaza kaydedildi.',error:'Öneri gönderilemedi. Yeniden dene.',idea:'Yeni özellik',bug:'Sorun / hata',content:'Öğrenme içeriği',conversation:'Conversation Coach',other:'Diğer',hubAria:'Öğrenme alanları',hubSummary:{academy:'A1–C2 yapılandırılmış öğrenme rotasında ilerle.',games:'Kelime, dinleme, yazma veya cümle pratiği seç.',stories:'Seviyene uygun özgün hikâyelerle bağlam içinde öğren.',speak:'Telaffuz çalış ve Conversation Coach ile konuş.',collections:'Akıllı tekrarlarını ve kişisel kelime listelerini aç.',progress:'Kurs PP, doğruluk, tekrar ve lig durumunu incele.'},gamesEye:'PRATİK MERKEZİ',gamesTitle:'Bir çalışma modu seç',speakEye:'DİNLE & KONUŞ',speakTitle:'Ses ve konuşma merkezi',speakDesc:'Aktif kursunda dinleme, telaffuz ve güvenli AI konuşma pratiği.',storiesEye:'OKU & PEKİŞTİR',storiesTitle:'Hikâyeler ve kişisel plan',storiesDesc:'Bağlam içinde öğren; tekrarlarını otomatik önceliklendir.',collectionsEye:'KELİME KOLEKSİYONLARI',collectionsTitle:'Hazır listelerle çalış',progressEye:'KURS İLERLEMESİ',progressTitle:'Puan, lig ve gelişim analizi',progressDesc:'Her hedef dilin ilerlemesi ayrı tutulur.',scoreEye:'DİL BAZLI PUANLAMA',scoreTitle:'Her kursun puanı ayrı',scoreNote:'Genel PP yalnızca lig için birleşir'},
 ru:{ideas:'Предложения и новинки',ideasShort:'Идеи',feedbackTitle:'Помогите развивать WordPilot',feedbackDesc:'Предложите функцию, сообщите об ошибке или запросите новый учебный материал.',category:'Категория',subject:'Краткий заголовок',message:'Ваше предложение',messagePh:'Опишите, что следует улучшить…',send:'Отправить',close:'Закрыть',privacy:'Не указывайте пароли, платёжные или конфиденциальные данные.',login:'Войдите через Google, чтобы безопасно отправить предложение.',sent:'Спасибо. Предложение отправлено.',saved:'Черновик сохранён на этом устройстве.',error:'Не удалось отправить предложение.',idea:'Новая функция',bug:'Ошибка',content:'Учебный материал',conversation:'Conversation Coach',other:'Другое',hubAria:'Разделы обучения',hubSummary:{academy:'Следуйте структурированному маршруту A1–C2.',games:'Выберите лексику, аудирование, письмо или предложения.',stories:'Читайте оригинальные тексты своего уровня.',speak:'Тренируйте произношение и говорите с Conversation Coach.',collections:'Откройте умные повторы и личные списки.',progress:'Смотрите PP, точность, повторы и лигу.'},gamesEye:'ЦЕНТР ПРАКТИКИ',gamesTitle:'Выберите режим практики',speakEye:'СЛУШАЙТЕ И ГОВОРИТЕ',speakTitle:'Центр речи и аудирования',speakDesc:'Аудирование, произношение и безопасная практика с ИИ.',storiesEye:'ЧИТАЙТЕ И ЗАКРЕПЛЯЙТЕ',storiesTitle:'Истории и личный план',storiesDesc:'Учитесь в контексте и автоматически планируйте повторения.',collectionsEye:'КОЛЛЕКЦИИ СЛОВ',collectionsTitle:'Занимайтесь по готовым спискам',progressEye:'ПРОГРЕСС КУРСА',progressTitle:'PP, лига и анализ развития',progressDesc:'Прогресс каждого языка хранится отдельно.',scoreEye:'ОЦЕНКА ПО ЯЗЫКАМ',scoreTitle:'У каждого курса свой счёт',scoreNote:'Общий PP объединяется только для лиги'},
 uz:{ideas:'Taklif va yangiliklar',ideasShort:'Taklif',feedbackTitle:'WordPilot’ni birga rivojlantiraylik',feedbackDesc:'Yangi funksiya taklif qiling, xatoni bildiring yoki yangi o‘quv materiali so‘rang.',category:'Toifa',subject:'Qisqa sarlavha',message:'Taklifingiz',messagePh:'Nimani yaxshilash kerakligini yozing…',send:'Taklifni yuborish',close:'Yopish',privacy:'Parol, to‘lov yoki maxfiy shaxsiy ma’lumot yozmang.',login:'Taklifni xavfsiz yuborish uchun Google orqali kiring.',sent:'Rahmat. Taklif yuborildi.',saved:'Qoralama ushbu qurilmada saqlandi.',error:'Taklif yuborilmadi.',idea:'Yangi funksiya',bug:'Xato',content:'O‘quv materiali',conversation:'Conversation Coach',other:'Boshqa',hubAria:'O‘quv bo‘limlari',hubSummary:{academy:'A1–C2 tartibli o‘quv yo‘lida davom eting.',games:'Lug‘at, tinglash, yozish yoki gap mashqini tanlang.',stories:'Darajangizga mos original hikoyalarni o‘qing.',speak:'Talaffuzni mashq qiling va Conversation Coach bilan gaplashing.',collections:'Aqlli takror va shaxsiy ro‘yxatlarni oching.',progress:'PP, aniqlik, takror va liga holatini ko‘ring.'},gamesEye:'MASHQ MARKAZI',gamesTitle:'Mashq turini tanlang',speakEye:'TINGLANG VA GAPIRING',speakTitle:'Ovoz va suhbat markazi',speakDesc:'Faol kursingizda tinglash, talaffuz va xavfsiz AI suhbati.',storiesEye:'O‘QING VA MUSTAHKAMLANG',storiesTitle:'Hikoyalar va shaxsiy reja',storiesDesc:'Kontekstda o‘rganing va takrorlarni avtomatik rejalang.',collectionsEye:'SO‘Z TO‘PLAMLARI',collectionsTitle:'Tayyor ro‘yxatlar bilan ishlang',progressEye:'KURS RIVOJI',progressTitle:'PP, liga va rivoj tahlili',progressDesc:'Har bir til rivoji alohida saqlanadi.',scoreEye:'TIL BO‘YICHA BALL',scoreTitle:'Har bir kursning bali alohida',scoreNote:'Umumiy PP faqat liga uchun birlashadi'},
 es:{ideas:'Sugerencias y novedades',ideasShort:'Ideas',feedbackTitle:'Ayúdanos a mejorar WordPilot',feedbackDesc:'Propón una función, informa de un error o solicita nuevo contenido.',category:'Categoría',subject:'Título breve',message:'Tu sugerencia',messagePh:'Describe qué te gustaría mejorar…',send:'Enviar sugerencia',close:'Cerrar',privacy:'No incluyas contraseñas, pagos ni datos personales sensibles.',login:'Inicia sesión con Google para enviar la sugerencia.',sent:'Gracias. La sugerencia fue enviada.',saved:'El borrador se guardó en este dispositivo.',error:'No se pudo enviar.',idea:'Nueva función',bug:'Problema / error',content:'Contenido educativo',conversation:'Conversation Coach',other:'Otro',hubAria:'Áreas de aprendizaje',hubSummary:{academy:'Sigue una ruta estructurada de A1 a C2.',games:'Elige vocabulario, escucha, escritura u oraciones.',stories:'Lee historias originales adaptadas a tu nivel.',speak:'Practica pronunciación y habla con Conversation Coach.',collections:'Abre repasos inteligentes y listas personales.',progress:'Consulta PP, precisión, repasos y liga.'},gamesEye:'CENTRO DE PRÁCTICA',gamesTitle:'Elige un modo de práctica',speakEye:'ESCUCHA Y HABLA',speakTitle:'Centro de voz y conversación',speakDesc:'Escucha, pronunciación y práctica segura con IA.',storiesEye:'LEE Y REFUERZA',storiesTitle:'Historias y plan personal',storiesDesc:'Aprende en contexto y prioriza los repasos.',collectionsEye:'COLECCIONES DE PALABRAS',collectionsTitle:'Estudia con listas preparadas',progressEye:'PROGRESO DEL CURSO',progressTitle:'PP, liga y análisis de progreso',progressDesc:'Cada idioma mantiene su propio progreso.',scoreEye:'PUNTUACIÓN POR IDIOMA',scoreTitle:'Cada curso tiene su puntuación',scoreNote:'El PP global solo se combina para la liga'},
 de:{ideas:'Ideen & Neuerungen',ideasShort:'Ideen',feedbackTitle:'WordPilot gemeinsam verbessern',feedbackDesc:'Schlage eine Funktion vor, melde einen Fehler oder wünsche neue Lerninhalte.',category:'Kategorie',subject:'Kurzer Titel',message:'Dein Vorschlag',messagePh:'Beschreibe, was verbessert werden soll…',send:'Vorschlag senden',close:'Schließen',privacy:'Keine Passwörter, Zahlungsdaten oder sensiblen Daten eingeben.',login:'Melde dich mit Google an, um den Vorschlag sicher zu senden.',sent:'Danke. Der Vorschlag wurde gesendet.',saved:'Der Entwurf wurde auf diesem Gerät gespeichert.',error:'Der Vorschlag konnte nicht gesendet werden.',idea:'Neue Funktion',bug:'Problem / Fehler',content:'Lerninhalt',conversation:'Conversation Coach',other:'Sonstiges',hubAria:'Lernbereiche',hubSummary:{academy:'Folge einem strukturierten A1–C2-Lernweg.',games:'Wähle Wortschatz, Hören, Schreiben oder Sätze.',stories:'Lies originale Geschichten auf deinem Niveau.',speak:'Übe Aussprache und sprich mit dem Conversation Coach.',collections:'Öffne intelligente Wiederholungen und Wortlisten.',progress:'Sieh PP, Genauigkeit, Wiederholungen und Liga.'},gamesEye:'ÜBUNGSZENTRUM',gamesTitle:'Übungsmodus wählen',speakEye:'HÖREN & SPRECHEN',speakTitle:'Sprach- und Gesprächszentrum',speakDesc:'Hören, Aussprache und sichere KI-Sprechpraxis.',storiesEye:'LESEN & FESTIGEN',storiesTitle:'Geschichten und persönlicher Plan',storiesDesc:'Im Kontext lernen und Wiederholungen priorisieren.',collectionsEye:'WORTSAMMLUNGEN',collectionsTitle:'Mit vorbereiteten Listen lernen',progressEye:'KURSFORTSCHRITT',progressTitle:'PP, Liga und Entwicklungsanalyse',progressDesc:'Jede Zielsprache hat eigenen Fortschritt.',scoreEye:'SPRACHBEZOGENE PUNKTE',scoreTitle:'Jeder Kurs hat eigene Punkte',scoreNote:'Globales PP wird nur für die Liga kombiniert'},
 fr:{ideas:'Suggestions et nouveautés',ideasShort:'Idées',feedbackTitle:'Améliorons WordPilot ensemble',feedbackDesc:'Proposez une fonction, signalez un problème ou demandez un nouveau contenu.',category:'Catégorie',subject:'Titre court',message:'Votre suggestion',messagePh:'Décrivez ce que vous souhaitez améliorer…',send:'Envoyer',close:'Fermer',privacy:'N’indiquez pas de mot de passe, paiement ou donnée sensible.',login:'Connectez-vous avec Google pour envoyer la suggestion.',sent:'Merci. La suggestion a été envoyée.',saved:'Le brouillon a été enregistré sur cet appareil.',error:'Impossible d’envoyer la suggestion.',idea:'Nouvelle fonction',bug:'Problème / bug',content:'Contenu pédagogique',conversation:'Conversation Coach',other:'Autre',hubAria:'Espaces d’apprentissage',hubSummary:{academy:'Suivez un parcours structuré de A1 à C2.',games:'Choisissez vocabulaire, écoute, écriture ou phrases.',stories:'Lisez des histoires originales adaptées à votre niveau.',speak:'Travaillez la prononciation et parlez avec Conversation Coach.',collections:'Ouvrez les révisions intelligentes et vos listes.',progress:'Consultez PP, précision, révisions et ligue.'},gamesEye:'CENTRE DE PRATIQUE',gamesTitle:'Choisissez un mode de pratique',speakEye:'ÉCOUTER & PARLER',speakTitle:'Centre vocal et conversation',speakDesc:'Écoute, prononciation et pratique sécurisée avec l’IA.',storiesEye:'LIRE & RENFORCER',storiesTitle:'Histoires et plan personnel',storiesDesc:'Apprenez en contexte et priorisez les révisions.',collectionsEye:'COLLECTIONS DE MOTS',collectionsTitle:'Étudiez avec des listes préparées',progressEye:'PROGRÈS DU COURS',progressTitle:'PP, ligue et analyse des progrès',progressDesc:'Chaque langue conserve sa progression.',scoreEye:'SCORE PAR LANGUE',scoreTitle:'Chaque cours a son score',scoreNote:'Le PP global est combiné uniquement pour la ligue'},
 it:{ideas:'Suggerimenti e novità',ideasShort:'Idee',feedbackTitle:'Miglioriamo WordPilot insieme',feedbackDesc:'Proponi una funzione, segnala un problema o richiedi nuovi contenuti.',category:'Categoria',subject:'Titolo breve',message:'Il tuo suggerimento',messagePh:'Descrivi cosa vorresti migliorare…',send:'Invia suggerimento',close:'Chiudi',privacy:'Non inserire password, pagamenti o dati personali sensibili.',login:'Accedi con Google per inviare il suggerimento.',sent:'Grazie. Suggerimento inviato.',saved:'La bozza è stata salvata sul dispositivo.',error:'Impossibile inviare il suggerimento.',idea:'Nuova funzione',bug:'Problema / bug',content:'Contenuto didattico',conversation:'Conversation Coach',other:'Altro',hubAria:'Aree di apprendimento',hubSummary:{academy:'Segui un percorso strutturato A1–C2.',games:'Scegli lessico, ascolto, scrittura o frasi.',stories:'Leggi storie originali adatte al tuo livello.',speak:'Esercita la pronuncia e parla con Conversation Coach.',collections:'Apri ripassi intelligenti e liste personali.',progress:'Visualizza PP, precisione, ripassi e lega.'},gamesEye:'CENTRO PRATICA',gamesTitle:'Scegli una modalità di pratica',speakEye:'ASCOLTA E PARLA',speakTitle:'Centro voce e conversazione',speakDesc:'Ascolto, pronuncia e pratica sicura con IA.',storiesEye:'LEGGI E RAFFORZA',storiesTitle:'Storie e piano personale',storiesDesc:'Impara nel contesto e dai priorità ai ripassi.',collectionsEye:'RACCOLTE DI PAROLE',collectionsTitle:'Studia con liste preparate',progressEye:'PROGRESSO DEL CORSO',progressTitle:'PP, lega e analisi dei progressi',progressDesc:'Ogni lingua conserva progressi separati.',scoreEye:'PUNTEGGIO PER LINGUA',scoreTitle:'Ogni corso ha un punteggio separato',scoreNote:'L’PP globale si combina solo per la lega'},
 pt:{ideas:'Sugestões e novidades',ideasShort:'Ideias',feedbackTitle:'Vamos melhorar o WordPilot',feedbackDesc:'Sugira uma função, comunique um erro ou peça novo conteúdo.',category:'Categoria',subject:'Título curto',message:'A sua sugestão',messagePh:'Descreva o que gostaria de melhorar…',send:'Enviar sugestão',close:'Fechar',privacy:'Não inclua palavras-passe, pagamentos ou dados sensíveis.',login:'Inicie sessão com Google para enviar a sugestão.',sent:'Obrigado. A sugestão foi enviada.',saved:'O rascunho foi guardado neste dispositivo.',error:'Não foi possível enviar.',idea:'Nova função',bug:'Problema / erro',content:'Conteúdo educativo',conversation:'Conversation Coach',other:'Outro',hubAria:'Áreas de aprendizagem',hubSummary:{academy:'Siga um percurso estruturado A1–C2.',games:'Escolha vocabulário, audição, escrita ou frases.',stories:'Leia histórias originais adequadas ao seu nível.',speak:'Pratique pronúncia e fale com o Conversation Coach.',collections:'Abra revisões inteligentes e listas pessoais.',progress:'Veja PP, precisão, revisões e liga.'},gamesEye:'CENTRO DE PRÁTICA',gamesTitle:'Escolha um modo de prática',speakEye:'OUVIR E FALAR',speakTitle:'Centro de voz e conversação',speakDesc:'Audição, pronúncia e prática segura com IA.',storiesEye:'LER E REFORÇAR',storiesTitle:'Histórias e plano pessoal',storiesDesc:'Aprenda em contexto e priorize revisões.',collectionsEye:'COLEÇÕES DE PALAVRAS',collectionsTitle:'Estude com listas preparadas',progressEye:'PROGRESSO DO CURSO',progressTitle:'PP, liga e análise de evolução',progressDesc:'Cada idioma mantém progresso separado.',scoreEye:'PONTUAÇÃO POR IDIOMA',scoreTitle:'Cada curso tem pontuação própria',scoreNote:'O PP global combina-se apenas para a liga'},
 ja:{ideas:'ご意見・新機能',ideasShort:'ご意見',feedbackTitle:'WordPilotを一緒に改善しましょう',feedbackDesc:'新機能の提案、不具合の報告、学習コンテンツの要望を送れます。',category:'カテゴリー',subject:'短いタイトル',message:'ご提案',messagePh:'改善してほしい内容を書いてください…',send:'送信',close:'閉じる',privacy:'パスワード、支払い情報、機密情報は入力しないでください。',login:'安全に送信するにはGoogleでログインしてください。',sent:'ありがとうございます。送信しました。',saved:'下書きをこの端末に保存しました。',error:'送信できませんでした。',idea:'新機能',bug:'不具合',content:'学習コンテンツ',conversation:'Conversation Coach',other:'その他',hubAria:'学習エリア',hubSummary:{academy:'A1からC2までの体系的な学習ルート。',games:'語彙、リスニング、作文、文の練習を選択。',stories:'レベルに合ったオリジナル物語を読む。',speak:'発音を練習しConversation Coachと会話。',collections:'スマート復習と個人単語リストを開く。',progress:'PP、正確さ、復習、リーグを確認。'},gamesEye:'練習センター',gamesTitle:'練習モードを選択',speakEye:'聞く・話す',speakTitle:'音声・会話センター',speakDesc:'リスニング、発音、安全なAI会話練習。',storiesEye:'読んで定着',storiesTitle:'物語と個人プラン',storiesDesc:'文脈で学び、復習を自動で優先します。',collectionsEye:'単語コレクション',collectionsTitle:'準備されたリストで学習',progressEye:'コース進捗',progressTitle:'PP・リーグ・成長分析',progressDesc:'言語ごとに進捗を保存します。',scoreEye:'言語別スコア',scoreTitle:'各コースに個別スコア',scoreNote:'総合PPはリーグのみで合算'},
 ko:{ideas:'제안 및 새 기능',ideasShort:'제안',feedbackTitle:'WordPilot을 함께 발전시켜요',feedbackDesc:'새 기능을 제안하고 오류나 학습 콘텐츠 요청을 보내세요.',category:'분류',subject:'짧은 제목',message:'제안 내용',messagePh:'개선할 내용을 자세히 적어 주세요…',send:'제안 보내기',close:'닫기',privacy:'비밀번호, 결제 정보, 민감한 개인정보는 입력하지 마세요.',login:'안전하게 보내려면 Google로 로그인하세요.',sent:'감사합니다. 제안이 전송되었습니다.',saved:'초안이 이 기기에 저장되었습니다.',error:'제안을 보내지 못했습니다.',idea:'새 기능',bug:'문제 / 오류',content:'학습 콘텐츠',conversation:'Conversation Coach',other:'기타',hubAria:'학습 영역',hubSummary:{academy:'A1–C2 구조화 학습 경로를 진행하세요.',games:'어휘, 듣기, 쓰기 또는 문장 연습을 선택하세요.',stories:'수준에 맞는 독창적인 이야기를 읽으세요.',speak:'발음을 연습하고 Conversation Coach와 대화하세요.',collections:'스마트 복습과 개인 단어 목록을 여세요.',progress:'PP, 정확도, 복습 및 리그를 확인하세요.'},gamesEye:'연습 센터',gamesTitle:'연습 모드 선택',speakEye:'듣기와 말하기',speakTitle:'음성 및 대화 센터',speakDesc:'듣기, 발음 및 안전한 AI 말하기 연습.',storiesEye:'읽고 강화하기',storiesTitle:'이야기와 개인 계획',storiesDesc:'문맥으로 배우고 복습 우선순위를 자동 설정합니다.',collectionsEye:'단어 모음',collectionsTitle:'준비된 목록으로 학습',progressEye:'코스 진행',progressTitle:'PP, 리그 및 성장 분석',progressDesc:'각 언어의 진행 상황이 따로 저장됩니다.',scoreEye:'언어별 점수',scoreTitle:'각 코스별 점수',scoreNote:'전체 PP는 리그에서만 합산'},
 zh:{ideas:'建议与新功能',ideasShort:'建议',feedbackTitle:'一起改进 WordPilot',feedbackDesc:'提出新功能、报告问题或申请新的学习内容。',category:'类别',subject:'简短标题',message:'您的建议',messagePh:'请说明希望改进的内容…',send:'发送建议',close:'关闭',privacy:'请勿填写密码、付款信息或敏感个人数据。',login:'请使用 Google 登录后安全发送。',sent:'谢谢，建议已发送。',saved:'草稿已保存在此设备。',error:'无法发送建议。',idea:'新功能',bug:'问题 / 错误',content:'学习内容',conversation:'Conversation Coach',other:'其他',hubAria:'学习区域',hubSummary:{academy:'按照 A1–C2 的结构化路线学习。',games:'选择词汇、听力、写作或句子练习。',stories:'阅读适合你水平的原创故事。',speak:'练习发音并与 Conversation Coach 对话。',collections:'打开智能复习和个人词表。',progress:'查看 PP、正确率、复习和联赛。'},gamesEye:'练习中心',gamesTitle:'选择练习模式',speakEye:'听与说',speakTitle:'语音与对话中心',speakDesc:'听力、发音和安全的 AI 口语练习。',storiesEye:'阅读与巩固',storiesTitle:'故事与个人计划',storiesDesc:'在语境中学习并自动安排复习。',collectionsEye:'词汇集合',collectionsTitle:'使用准备好的列表学习',progressEye:'课程进度',progressTitle:'PP、联赛与成长分析',progressDesc:'每种目标语言单独保存进度。',scoreEye:'按语言计分',scoreTitle:'每门课程单独计分',scoreNote:'总 PP 仅在联赛中合并'}
};
function wp712Text(){return WP712_TEXT[wp71LanguageProfile?.ui]||WP712_TEXT.en}
function wp712Set(selector,text){const el=$(selector);if(el&&text!==undefined)el.textContent=text}
function wp712ApplyHubTranslations(){
 const t=wp712Text(),hub=$('.learning-hub-tabs');if(hub)hub.setAttribute('aria-label',t.hubAria);
 const active=hub?.querySelector('[data-dashboard-tab].active');const summary=$('#wp65HubSummary');if(summary&&active)summary.textContent=t.hubSummary[active.dataset.dashboardTab]||'';
 wp712Set('[data-dashboard-panel="games"] .panel-head .eyebrow',t.gamesEye);wp712Set('[data-dashboard-panel="games"] .panel-head h3',t.gamesTitle);
 wp712Set('[data-dashboard-panel="speak"] .dashboard-panel-head .eyebrow',t.speakEye);wp712Set('[data-dashboard-panel="speak"] .dashboard-panel-head h2',t.speakTitle);wp712Set('[data-dashboard-panel="speak"] .dashboard-panel-head p:last-child',t.speakDesc);
 wp712Set('[data-dashboard-panel="stories"] .dashboard-panel-head .eyebrow',t.storiesEye);wp712Set('[data-dashboard-panel="stories"] .dashboard-panel-head h2',t.storiesTitle);wp712Set('[data-dashboard-panel="stories"] .dashboard-panel-head p:last-child',t.storiesDesc);
 wp712Set('[data-dashboard-panel="collections"] .collections-head .eyebrow',t.collectionsEye);wp712Set('[data-dashboard-panel="collections"] .collections-head h2',t.collectionsTitle);
 wp712Set('[data-dashboard-panel="progress"] .dashboard-panel-head .eyebrow',t.progressEye);wp712Set('[data-dashboard-panel="progress"] .dashboard-panel-head h2',t.progressTitle);wp712Set('[data-dashboard-panel="progress"] .dashboard-panel-head p:last-child',t.progressDesc);
 wp712Set('[data-dashboard-panel="progress"] .language-xp-head .eyebrow',t.scoreEye);wp712Set('#languageXpTitle',t.scoreTitle);wp712Set('[data-dashboard-panel="progress"] .language-xp-head>span',t.scoreNote);
}
function wp712RefreshFlags(){if(typeof wp65ApplyFlags==='function')wp65ApplyFlags();$$('.course-card[data-course]').forEach(card=>{const slot=card.querySelector('.course-flag');if(slot)slot.innerHTML=wp65FlagMarkup(card.dataset.course)})}
function wp712EnsureFeedback(){
 if(!$('#wp712FeedbackButton')){$('.top-actions')?.insertAdjacentHTML('afterbegin',`<button id="wp712FeedbackButton" class="wp712-feedback-button" type="button"><span>💡</span><small>${wp712Text().ideas}</small></button>`)}
 if(!$('#wp712FeedbackFab'))document.body.insertAdjacentHTML('beforeend',`<button id="wp712FeedbackFab" class="wp712-feedback-fab" type="button" aria-label="${wp712Text().ideas}">💡</button>`);
 if(!$('#wp712FeedbackCard'))$('.v7-command-center')?.insertAdjacentHTML('afterend',`<button id="wp712FeedbackCard" class="wp712-feedback-card" type="button"><span>💡</span><div><b>${wp712Text().ideas}</b><small>${wp712Text().feedbackDesc}</small></div><em>→</em></button>`);
 if(!$('#wp712FeedbackDialog'))document.body.insertAdjacentHTML('beforeend',`<dialog id="wp712FeedbackDialog" class="wp712-feedback-dialog"><div class="wp712-feedback-shell"><div class="wp712-feedback-head"><span>💡</span><div><h2></h2><p></p></div></div><form id="wp712FeedbackForm" class="wp712-feedback-form"><label><span data-f="category"></span><select id="wp712FeedbackCategory"><option value="idea"></option><option value="bug"></option><option value="content"></option><option value="conversation"></option><option value="other"></option></select></label><label><span data-f="subject"></span><input id="wp712FeedbackSubject" minlength="3" maxlength="120" required></label><label><span data-f="message"></span><textarea id="wp712FeedbackMessage" minlength="10" maxlength="2000" required></textarea></label><p class="wp712-feedback-note"></p><div id="wp712FeedbackStatus" class="wp712-feedback-status" aria-live="polite"></div><div class="wp712-feedback-actions"><button class="secondary" data-feedback-close type="button"></button><button class="primary" type="submit"></button></div></form></div></dialog>`);
 wp712TranslateFeedback();
}
function wp712TranslateFeedback(){
 const t=wp712Text(),btn=$('#wp712FeedbackButton small');if(btn)btn.textContent=t.ideas;const fab=$('#wp712FeedbackFab');if(fab)fab.setAttribute('aria-label',t.ideas);const card=$('#wp712FeedbackCard');if(card){card.querySelector('b').textContent=t.ideas;card.querySelector('small').textContent=t.feedbackDesc}
 const d=$('#wp712FeedbackDialog');if(!d)return;d.querySelector('h2').textContent=t.feedbackTitle;d.querySelector('.wp712-feedback-head p').textContent=t.feedbackDesc;d.querySelector('[data-f="category"]').textContent=t.category;d.querySelector('[data-f="subject"]').textContent=t.subject;d.querySelector('[data-f="message"]').textContent=t.message;d.querySelector('#wp712FeedbackSubject').placeholder=t.subject;d.querySelector('#wp712FeedbackMessage').placeholder=t.messagePh;d.querySelector('.wp712-feedback-note').textContent=t.privacy;d.querySelector('[data-feedback-close]').textContent=t.close;d.querySelector('[type="submit"]').textContent=t.send;
 const opts=d.querySelectorAll('option');[t.idea,t.bug,t.content,t.conversation,t.other].forEach((x,i)=>{if(opts[i])opts[i].textContent=x});
}
function wp712OpenFeedback(){wp712EnsureFeedback();const d=$('#wp712FeedbackDialog');let draft=null;try{draft=JSON.parse(localStorage.getItem(`${STORE}:feedback_draft`)||'null')}catch{}if(draft){$('#wp712FeedbackCategory').value=draft.category||'idea';$('#wp712FeedbackSubject').value=draft.subject||'';$('#wp712FeedbackMessage').value=draft.message||''}$('#wp712FeedbackStatus').textContent='';if(d&&!d.open)d.showModal()}
async function wp712SubmitFeedback(){
 const t=wp712Text(),status=$('#wp712FeedbackStatus'),category=$('#wp712FeedbackCategory').value,subject=$('#wp712FeedbackSubject').value.trim(),message=$('#wp712FeedbackMessage').value.trim();status.className='wp712-feedback-status';
 const draft={category,subject,message,updatedAt:new Date().toISOString()};localStorage.setItem(`${STORE}:feedback_draft`,JSON.stringify(draft));
 if(!authUser||!fbDb){status.textContent=t.login;status.classList.add('error');return}
 const submit=$('#wp712FeedbackForm [type="submit"]');submit.disabled=true;
 try{await fbDb.collection('feedback').add({uid:authUser.uid,name:accountDisplayName(profile?.name,authUser),email:authUser.email||'',category,subject,message,uiLanguage:wp71LanguageProfile.ui||wp71Support(),targetLanguage:activeCourse,appVersion:WP712_VERSION,page:location.pathname,status:'new',createdAt:window.firebase.firestore.FieldValue.serverTimestamp()});localStorage.removeItem(`${STORE}:feedback_draft`);$('#wp712FeedbackForm').reset();status.textContent=t.sent;status.classList.add('ok')}
 catch(error){console.error('Feedback submit error',error);status.textContent=t.error;status.classList.add('error')}
 finally{submit.disabled=false}
}

// Cache must include both target and explanation language. This also prevents stale Russian words after route changes.
loadCourseWords=async function(course=activeCourse){
 const support=wp71Support(),key=`${course}|${support}|712`;if(courseWordCache[key]){words=courseWordCache[key];return words}
 let data;
 if((course==='ru'||course==='uz')&&support==='tr'){
   const meta=COURSES[course],response=await fetch(`${meta.file}?v=${VERSION}`,{cache:'no-store'});if(!response.ok)throw new Error(meta.file);const raw=await response.json();data=raw.map(row=>normalizeCourseRecord(row,course));if(course==='ru'&&!russianAlphabet.length)await loadRussianAlphabet();
 }else{const concepts=await wp71LoadConcepts();data=concepts.map(c=>wp71ConceptToLegacy(c,course,support))}
 courseWordCache[key]=data;courseWordCache[course]=data;words=data;return data;
};
const wp712PrevApplyShell=wp711ApplyShell;
wp711ApplyShell=function(){const out=wp712PrevApplyShell();wp712ApplyHubTranslations();wp712EnsureFeedback();wp712RefreshFlags();const version=$('.version');if(version)version.textContent='v7.1.2';return out};
wp71ApplyInterfaceText=wp711ApplyShell;
const wp712PrevUpdateCourseUI=updateCourseUI;
updateCourseUI=function(){const out=wp712PrevUpdateCourseUI();const meta=COURSES[activeCourse],support=wp71Lang(wp71Support()).native;wp711SetText('#activeCourseSummary',`${meta.flag} ${meta.name} · ${meta.displayCount}`);const search=$('#searchInput');if(search)search.placeholder=wp711T('search',{target:meta.name,support});wp712RefreshFlags();wp712ApplyHubTranslations();return out};
const wp712PrevSwitchCourse=switchCourse;
switchCourse=async function(course){if(!COURSES[course])return;wp71SaveLanguageProfile({target:course});courseWordCache={};const result=await wp712PrevSwitchCourse(course);wp71LanguageProfile.target=course;wp71LanguageProfile.updatedAt=new Date().toISOString();localStorage.setItem(WP71_SETTINGS_KEY,JSON.stringify(wp71LanguageProfile));wp712RefreshFlags();wp712ApplyHubTranslations();return result};
function setupV712Events(){
 wp712EnsureFeedback();wp712ApplyHubTranslations();wp712RefreshFlags();
 document.addEventListener('click',e=>{if(e.target.closest('#wp712FeedbackButton,#wp712FeedbackFab,#wp712FeedbackCard')){wp712OpenFeedback();return}if(e.target.closest('[data-feedback-close]')){$('#wp712FeedbackDialog')?.close();return}if(e.target.closest('[data-dashboard-tab]'))setTimeout(wp712ApplyHubTranslations,0)});
 document.addEventListener('submit',e=>{if(e.target.id==='wp712FeedbackForm'){e.preventDefault();wp712SubmitFeedback()}});
}
function wp712AfterInit(){
 if(COURSES[wp71LanguageProfile.target]&&activeCourse!==wp71LanguageProfile.target){activeCourse=wp71LanguageProfile.target;profile.activeCourse=activeCourse;localStorage.setItem(ACTIVE_COURSE_KEY,activeCourse);courseWordCache={};loadCourseWords(activeCourse).then(()=>{updateCourseUI();renderAll();renderWords(true)}).catch(console.error)}
 wp712EnsureFeedback();wp712ApplyHubTranslations();wp712RefreshFlags();
}
