/* WordPilot v9.0.0 Tester Beta
   Conversation Coach 4.0, real-life scenario missions, Mira voice preference,
   smoothed speaking feedback and transcript-based pronunciation analysis.
   No private API key is stored in the browser. */
const WP83_VERSION='9.0.0';
const WP83_SESSION_SCHEMA=1;
let wp83PronunciationMode='word';
let wp83PronunciationStartedAt=0;
let wp83PronunciationConfidence=0;

const WP83_SCENARIOS={
  intro:{icon:'👋',title:'Tanışma',hint:'İlk kez tanıştığın biriyle doğal sohbet',place:'Yeni bir arkadaşla buluşma',role:'Mira seninle ilk kez tanışıyor.',goal:'Kendini tanıt, yaşadığın yeri söyle ve karşı tarafa bir soru sor.',turns:4,
    tasks:['Adını ve yaşadığın yeri söyle','Günlük hayatından bir ayrıntı paylaş','Mira’ya bir soru sor','Sohbeti doğal biçimde tamamla'],
    phrases:{en:['My name is …','I live in …','What about you?'],ru:['Меня зовут …','Я живу в …','А вы?'],uz:['Mening ismim …','Men …da yashayman','Siz-chi?'],tr:['Benim adım …','…da yaşıyorum','Peki ya sen?']},
    starters:{en:'Hi! I’m Mira. It’s nice to meet you. What’s your name, and where do you live?',ru:'Привет! Я Мира. Очень приятно. Как вас зовут и где вы живёте?',uz:'Salom! Men Miraman. Tanishganimdan xursandman. Ismingiz nima va qayerda yashaysiz?',tr:'Merhaba! Ben Mira. Tanıştığımıza memnun oldum. Adın ne ve nerede yaşıyorsun?'},
    questions:{en:['What do you usually do during the day?','What do you enjoy doing in your free time?','What would you like to know about me?','How would you end this conversation politely?'],ru:['Чем вы обычно занимаетесь днём?','Что вы любите делать в свободное время?','Что вы хотели бы узнать обо мне?','Как вы вежливо закончите этот разговор?'],uz:['Kunduzi odatda nima qilasiz?','Bo‘sh vaqtingizda nima qilishni yoqtirasiz?','Men haqimda nimani bilishni xohlaysiz?','Suhbatni qanday muloyim yakunlaysiz?'],tr:['Gün içinde genellikle ne yaparsın?','Boş zamanlarında ne yapmayı seversin?','Benim hakkımda ne öğrenmek istersin?','Bu konuşmayı kibarca nasıl bitirirsin?']},
    pron:{en:['Nice to meet you.','What do you do in your free time?'],ru:['Очень приятно.','Что вы делаете в свободное время?'],uz:['Tanishganimdan xursandman.','Bo‘sh vaqtingizda nima qilasiz?'],tr:['Tanıştığımıza memnun oldum.','Boş zamanlarında ne yaparsın?']}},
  airport:{icon:'✈️',title:'Havaalanı',hint:'Check-in, bagaj, kapı ve uçuş saati',place:'Uluslararası havaalanı',role:'Mira check-in görevlisi.',goal:'Uçuşunu bul, bagajını teslim et ve kapıyı öğren.',turns:5,
    tasks:['Nereye uçtuğunu söyle','Pasaport ve rezervasyon durumunu açıkla','Bagaj hakkında soru sor','Kapı ve biniş saatini öğren','Teşekkür ederek işlemi bitir'],
    phrases:{en:['I’m flying to …','I have one suitcase.','What time does boarding start?'],ru:['Я лечу в …','У меня один чемодан.','Когда начинается посадка?'],uz:['Men …ga uchyapman','Menda bitta chamadon bor','Samolyotga chiqish qachon boshlanadi?'],tr:['…ya uçuyorum','Bir valizim var','Biniş ne zaman başlıyor?']},
    starters:{en:'Good morning. Welcome to check-in. Where are you flying today?',ru:'Доброе утро. Добро пожаловать на регистрацию. Куда вы сегодня летите?',uz:'Xayrli tong. Ro‘yxatdan o‘tishga xush kelibsiz. Bugun qayerga uchasiz?',tr:'Günaydın. Check-in bölümüne hoş geldiniz. Bugün nereye uçuyorsunuz?'},
    questions:{en:['May I see your passport and booking confirmation?','How many bags would you like to check in?','Would you like an aisle or a window seat?','Do you know where gate B12 is?','Is there anything else you need before boarding?'],ru:['Можно ваш паспорт и подтверждение бронирования?','Сколько мест багажа вы сдаёте?','Вы предпочитаете место у прохода или у окна?','Вы знаете, где выход B12?','Вам ещё что-нибудь нужно перед посадкой?'],uz:['Pasportingiz va bron tasdiqini ko‘rsata olasizmi?','Nechta yuk topshirasiz?','Yo‘lak yoki deraza yonidagi joyni xohlaysizmi?','B12 darvozasi qayerdaligini bilasizmi?','Samolyotga chiqishdan oldin yana biror narsa kerakmi?'],tr:['Pasaportunuzu ve rezervasyonunuzu görebilir miyim?','Kaç parça bagaj vereceksiniz?','Koridor mu pencere kenarı mı istersiniz?','B12 kapısının nerede olduğunu biliyor musunuz?','Binişten önce başka bir şeye ihtiyacınız var mı?']},
    pron:{en:['Where is the boarding gate?','I have one suitcase to check in.'],ru:['Где выход на посадку?','У меня один чемодан.'],uz:['Samolyotga chiqish darvozasi qayerda?','Menda bitta chamadon bor.'],tr:['Biniş kapısı nerede?','Bir valizim var.']}},
  hotel:{icon:'🏨',title:'Otel',hint:'Rezervasyon, oda ve otel hizmetleri',place:'Otel resepsiyonu',role:'Mira resepsiyon görevlisi.',goal:'Rezervasyonunu doğrula, oda ayrıntılarını öğren ve bir talepte bulun.',turns:5,
    tasks:['Rezervasyon adını söyle','Kaç gece kalacağını belirt','Kahvaltı veya Wi-Fi hakkında soru sor','Odayla ilgili bir istekte bulun','Çıkış saatini öğren'],
    phrases:{en:['I have a reservation.','I’m staying for three nights.','What time is check-out?'],ru:['У меня есть бронь.','Я остановлюсь на три ночи.','Во сколько выезд?'],uz:['Menda bron bor.','Men uch kecha qolaman.','Mehmonxonadan chiqish soati nechada?'],tr:['Rezervasyonum var','Üç gece kalacağım','Çıkış saati kaçta?']},
    starters:{en:'Welcome to the hotel. Do you have a reservation with us?',ru:'Добро пожаловать в отель. У вас есть бронь?',uz:'Mehmonxonamizga xush kelibsiz. Bron qilganmisiz?',tr:'Otelimize hoş geldiniz. Rezervasyonunuz var mı?'},
    questions:{en:['What name is the reservation under?','How many nights will you be staying?','Would you like information about breakfast and Wi-Fi?','Is there anything you need in your room?','Would you like me to explain the check-out time?'],ru:['На какое имя бронь?','На сколько ночей вы останетесь?','Рассказать о завтраке и Wi-Fi?','Вам что-нибудь нужно в номер?','Объяснить время выезда?'],uz:['Bron qaysi ismga qilingan?','Necha kecha qolasiz?','Nonushta va Wi-Fi haqida ma’lumot kerakmi?','Xonangiz uchun biror narsa kerakmi?','Chiqish vaqtini tushuntirib beraymi?'],tr:['Rezervasyon hangi isimle yapılmıştı?','Kaç gece kalacaksınız?','Kahvaltı ve Wi-Fi hakkında bilgi ister misiniz?','Odanız için ihtiyacınız olan bir şey var mı?','Çıkış saatini açıklamamı ister misiniz?']},
    pron:{en:['I have a reservation under the name Aslan.','Could I have a quiet room, please?'],ru:['У меня бронь на фамилию Аслан.','Можно тихий номер, пожалуйста?'],uz:['Aslan nomiga bronim bor.','Iltimos, tinch xona bersangiz.'],tr:['Aslan adına rezervasyonum var.','Sessiz bir oda alabilir miyim?']}},
  restaurant:{icon:'🍽️',title:'Restoran',hint:'Masa, sipariş, tercih ve hesap',place:'Yoğun bir restoran',role:'Mira garson.',goal:'Masa iste, yemek sipariş et, bir tercihini açıkla ve hesabı iste.',turns:5,
    tasks:['Kaç kişilik masa istediğini söyle','İçecek sipariş et','Ana yemek seç','Bir alerji veya tercihi açıkla','Hesabı iste'],
    phrases:{en:['A table for two, please.','I’d like …','Could we have the bill, please?'],ru:['Столик на двоих, пожалуйста.','Я бы хотел(а) …','Можно счёт, пожалуйста?'],uz:['Ikki kishilik stol, iltimos.','Men … xohlayman','Hisobni olib kelsangiz.'],tr:['İki kişilik masa lütfen','… istiyorum','Hesabı alabilir miyiz?']},
    starters:{en:'Good evening. How many people are in your party?',ru:'Добрый вечер. Сколько вас человек?',uz:'Xayrli kech. Necha kishisiz?',tr:'İyi akşamlar. Kaç kişisiniz?'},
    questions:{en:['Would you like something to drink first?','Are you ready to order your main course?','Do you have any allergies or dietary preferences?','How would you like your meal prepared?','Would you like dessert, or shall I bring the bill?'],ru:['Сначала будете что-нибудь пить?','Вы готовы заказать основное блюдо?','У вас есть аллергия или особые предпочтения?','Как приготовить ваше блюдо?','Хотите десерт или принести счёт?'],uz:['Avval ichimlik buyurtma qilasizmi?','Asosiy taomni buyurtma qilishga tayyormisiz?','Allergiyangiz yoki ovqatlanish bo‘yicha talabangiz bormi?','Taomingiz qanday tayyorlansin?','Shirinlik xohlaysizmi yoki hisobni olib kelaymi?'],tr:['Önce içecek ister misiniz?','Ana yemeği sipariş etmeye hazır mısınız?','Alerjiniz veya beslenme tercihiniz var mı?','Yemeğiniz nasıl hazırlansın?','Tatlı ister misiniz, yoksa hesabı getireyim mi?']},
    pron:{en:['A table for two, please.','Could we have the bill, please?'],ru:['Столик на двоих, пожалуйста.','Можно счёт, пожалуйста?'],uz:['Ikki kishilik stol, iltimos.','Hisobni olib kelsangiz.'],tr:['İki kişilik masa lütfen.','Hesabı alabilir miyiz?']}},
  shopping:{icon:'🛍️',title:'Alışveriş',hint:'Ürün, beden, fiyat ve ödeme',place:'Bir mağaza',role:'Mira mağaza görevlisi.',goal:'Aradığın ürünü tarif et, beden veya renk sor ve ödeme yap.',turns:5,
    tasks:['Aradığın ürünü söyle','Beden veya renk belirt','Fiyatı sor','Ürünü denemek iste','Ödeme yöntemini söyle'],
    phrases:{en:['I’m looking for …','Do you have this in a larger size?','Can I pay by card?'],ru:['Я ищу …','Есть размер побольше?','Можно оплатить картой?'],uz:['Men … qidiryapman','Buning kattaroq o‘lchami bormi?','Karta bilan to‘lasam bo‘ladimi?'],tr:['… arıyorum','Bunun daha büyük bedeni var mı?','Kartla ödeyebilir miyim?']},
    starters:{en:'Hello! Can I help you find something today?',ru:'Здравствуйте! Вам помочь что-нибудь найти?',uz:'Salom! Biror narsa topishga yordam beraymi?',tr:'Merhaba! Bir şey bulmanıza yardımcı olabilir miyim?'},
    questions:{en:['What kind of item are you looking for?','Which size and colour would you prefer?','Would you like to know the price?','Would you like to try it on?','How would you like to pay?'],ru:['Что именно вы ищете?','Какой размер и цвет вам нужен?','Сказать цену?','Хотите примерить?','Как будете оплачивать?'],uz:['Qanday mahsulot qidiryapsiz?','Qaysi o‘lcham va rangni xohlaysiz?','Narxini bilishni xohlaysizmi?','Kiyib ko‘rmoqchimisiz?','Qanday to‘laysiz?'],tr:['Nasıl bir ürün arıyorsunuz?','Hangi beden ve rengi tercih edersiniz?','Fiyatını öğrenmek ister misiniz?','Denemek ister misiniz?','Nasıl ödeme yapmak istersiniz?']},
    pron:{en:['Do you have this in a medium?','Can I pay by card?'],ru:['Есть это среднего размера?','Можно оплатить картой?'],uz:['Buning o‘rta o‘lchami bormi?','Karta bilan to‘lasam bo‘ladimi?'],tr:['Bunun orta bedeni var mı?','Kartla ödeyebilir miyim?']}},
  health:{icon:'🩺',title:'Doktor',hint:'Belirti, süre ve basit sağlık görüşmesi',place:'Bir sağlık merkezi',role:'Mira sağlık görevlisi.',goal:'Belirtini, ne zamandır sürdüğünü ve şiddetini açıkla.',turns:5,
    tasks:['Ana şikâyetini söyle','Ne zamandır sürdüğünü belirt','Şiddetini tarif et','Başka belirti olup olmadığını söyle','Sorulan güvenlik sorusunu yanıtla'],
    phrases:{en:['I have a headache.','It started two days ago.','The pain is mild.'],ru:['У меня болит голова.','Это началось два дня назад.','Боль слабая.'],uz:['Boshim og‘riyapti.','Bu ikki kun oldin boshlandi.','Og‘riq yengil.'],tr:['Başım ağrıyor','İki gün önce başladı','Ağrı hafif']},
    starters:{en:'Hello. I’ll ask a few simple questions. What seems to be the problem today?',ru:'Здравствуйте. Я задам несколько простых вопросов. Что вас беспокоит?',uz:'Salom. Bir nechta oddiy savol beraman. Bugun nimadan shikoyatingiz bor?',tr:'Merhaba. Birkaç basit soru soracağım. Bugünkü şikâyetiniz nedir?'},
    questions:{en:['When did the problem start?','How strong is the pain from one to ten?','Do you have any other symptoms?','Does anything make it better or worse?','Are you taking any regular medicine?'],ru:['Когда это началось?','Насколько сильная боль по шкале от одного до десяти?','Есть другие симптомы?','Что-нибудь улучшает или ухудшает состояние?','Вы принимаете постоянные лекарства?'],uz:['Bu qachon boshlandi?','Og‘riq bir dan o‘ngacha nechchi?','Boshqa alomatlar bormi?','Nima holatni yaxshilaydi yoki yomonlashtiradi?','Doimiy dori qabul qilasizmi?'],tr:['Bu ne zaman başladı?','Ağrı birden ona kadar kaç şiddetinde?','Başka bir belirtiniz var mı?','Ağrıyı artıran veya azaltan bir şey var mı?','Düzenli kullandığınız bir ilaç var mı?']},
    pron:{en:['It started two days ago.','The pain is about five out of ten.'],ru:['Это началось два дня назад.','Боль примерно пять из десяти.'],uz:['Bu ikki kun oldin boshlandi.','Og‘riq o‘ndan besh darajada.'],tr:['İki gün önce başladı.','Ağrı on üzerinden beş.']}},
  university:{icon:'🎓',title:'Üniversite',hint:'Ders, bölüm, danışman ve kampüs',place:'Üniversite öğrenci işleri',role:'Mira akademik danışman.',goal:'Bölümünü anlat, ders seçimi sor ve akademik hedefini açıkla.',turns:5,
    tasks:['Bölümünü veya alanını söyle','Bir ders hakkında soru sor','Program sorununu açıkla','Akademik hedefini anlat','Bir sonraki adımı netleştir'],
    phrases:{en:['I study …','I have a question about this course.','What should I do next?'],ru:['Я изучаю …','У меня вопрос по этому курсу.','Что мне делать дальше?'],uz:['Men … yo‘nalishida o‘qiyman','Bu fan haqida savolim bor','Keyin nima qilishim kerak?'],tr:['… bölümünde okuyorum','Bu ders hakkında sorum var','Bundan sonra ne yapmalıyım?']},
    starters:{en:'Hello. I’m your academic adviser today. What are you studying?',ru:'Здравствуйте. Сегодня я ваш академический консультант. Что вы изучаете?',uz:'Salom. Bugun men akademik maslahatchingizman. Qaysi yo‘nalishda o‘qiysiz?',tr:'Merhaba. Bugün akademik danışmanınızım. Hangi alanda eğitim alıyorsunuz?'},
    questions:{en:['Which course would you like to discuss?','What difficulty are you having with your schedule?','What is your main academic goal this term?','Have you spoken to the course instructor?','What action will you take after this meeting?'],ru:['Какой курс вы хотите обсудить?','Какая проблема у вас с расписанием?','Какова ваша главная учебная цель на этот семестр?','Вы говорили с преподавателем курса?','Что вы сделаете после этой встречи?'],uz:['Qaysi fanni muhokama qilmoqchisiz?','Jadvalingizda qanday muammo bor?','Bu semestrdagi asosiy akademik maqsadingiz nima?','Fan o‘qituvchisi bilan gaplashdingizmi?','Bu uchrashuvdan keyin nima qilasiz?'],tr:['Hangi dersi konuşmak istiyorsunuz?','Ders programınızda nasıl bir sorun var?','Bu dönemki ana akademik hedefiniz nedir?','Dersin öğretim elemanıyla konuştunuz mu?','Bu görüşmeden sonra hangi adımı atacaksınız?']},
    pron:{en:['I have a question about my course schedule.','What should I do next?'],ru:['У меня вопрос о расписании занятий.','Что мне делать дальше?'],uz:['Dars jadvalim haqida savolim bor.','Keyin nima qilishim kerak?'],tr:['Ders programım hakkında sorum var.','Bundan sonra ne yapmalıyım?']}},
  interview:{icon:'💼',title:'İş görüşmesi',hint:'Deneyim, güçlü yön ve hedefler',place:'Çevrim içi iş görüşmesi',role:'Mira işe alım uzmanı.',goal:'Kendini profesyonel biçimde tanıt, deneyimini ve güçlü yönünü açıkla.',turns:6,
    tasks:['Kendini profesyonel tanıt','Deneyimini özetle','Bir güçlü yönünü örnekle açıkla','İlanla neden ilgilendiğini söyle','Bir gelişim alanından bahset','Görüşmeciye soru sor'],
    phrases:{en:['I have experience in …','One of my strengths is …','I’m interested in this role because …'],ru:['У меня есть опыт в …','Одна из моих сильных сторон — …','Эта должность интересна мне, потому что …'],uz:['Menda … bo‘yicha tajriba bor','Kuchli tomonlarimdan biri …','Bu lavozimga qiziqishimning sababi …'],tr:['… konusunda deneyimim var','Güçlü yönlerimden biri …','Bu pozisyonla ilgileniyorum çünkü …']},
    starters:{en:'Welcome. Let’s begin with a short introduction. Could you tell me about yourself?',ru:'Добро пожаловать. Начнём с короткого представления. Расскажите немного о себе.',uz:'Xush kelibsiz. Qisqa tanishtirishdan boshlaymiz. O‘zingiz haqingizda ayta olasizmi?',tr:'Hoş geldiniz. Kısa bir tanıtımla başlayalım. Kendinizden bahseder misiniz?'},
    questions:{en:['What experience is most relevant to this role?','Could you give an example of one of your strengths?','Why are you interested in this position?','Tell me about a skill you are currently improving.','How do you handle a difficult task?','What would you like to ask us?'],ru:['Какой ваш опыт наиболее подходит для этой должности?','Приведите пример одной из ваших сильных сторон.','Почему вас интересует эта должность?','Какой навык вы сейчас развиваете?','Как вы справляетесь со сложной задачей?','Что вы хотели бы спросить у нас?'],uz:['Qaysi tajribangiz bu lavozimga eng mos?','Kuchli tomoningizga bir misol keltira olasizmi?','Nega bu lavozim sizni qiziqtiradi?','Hozir qaysi ko‘nikmangizni rivojlantiryapsiz?','Qiyin vazifani qanday bajarasiz?','Bizdan nimani so‘ramoqchisiz?'],tr:['Bu pozisyonla en ilgili deneyiminiz hangisidir?','Güçlü yönlerinizden birine örnek verebilir misiniz?','Bu pozisyonla neden ilgileniyorsunuz?','Şu anda geliştirdiğiniz bir beceriniz nedir?','Zor bir görevle nasıl başa çıkarsınız?','Bize ne sormak istersiniz?']},
    pron:{en:['One of my strengths is clear communication.','I’m interested in this role because it matches my experience.'],ru:['Одна из моих сильных сторон — ясное общение.','Эта должность соответствует моему опыту.'],uz:['Kuchli tomonlarimdan biri aniq muloqotdir.','Bu lavozim tajribamga mos keladi.'],tr:['Güçlü yönlerimden biri açık iletişimdir.','Bu pozisyon deneyimime uyduğu için ilgileniyorum.']}},
  directions:{icon:'🗺️',title:'Yol tarifi',hint:'Konum, yön ve toplu taşıma',place:'Şehir merkezinde bir sokak',role:'Mira yerel bir şehir sakini.',goal:'Gitmek istediğin yeri söyle, yön sor ve tarifi doğrula.',turns:4,
    tasks:['Gitmek istediğin yeri söyle','Nasıl gideceğini sor','Bir yönü tekrar doğrula','Teşekkür et'],
    phrases:{en:['How can I get to …?','Should I turn left here?','Thank you for your help.'],ru:['Как пройти к …?','Здесь нужно повернуть налево?','Спасибо за помощь.'],uz:['…ga qanday borsam bo‘ladi?','Bu yerdan chapga burilaymi?','Yordamingiz uchun rahmat.'],tr:['…ya nasıl gidebilirim?','Buradan sola mı dönmeliyim?','Yardımınız için teşekkür ederim.']},
    starters:{en:'Hi. You look a little lost. Where would you like to go?',ru:'Здравствуйте. Кажется, вы заблудились. Куда вы хотите попасть?',uz:'Salom. Adashganga o‘xshaysiz. Qayerga bormoqchisiz?',tr:'Merhaba. Biraz kaybolmuş görünüyorsunuz. Nereye gitmek istiyorsunuz?'},
    questions:{en:['Are you walking or using public transport?','Would you like the quickest or the easiest route?','Can you repeat the first direction to check it?','Do you need help with anything else?'],ru:['Вы идёте пешком или на транспорте?','Вам нужен самый быстрый или самый простой маршрут?','Повторите первое направление, чтобы проверить.','Вам ещё чем-нибудь помочь?'],uz:['Piyoda ketasizmi yoki jamoat transportidami?','Eng tez yoki eng oson yo‘lni xohlaysizmi?','Birinchi yo‘nalishni tekshirish uchun takrorlay olasizmi?','Yana yordam kerakmi?'],tr:['Yürüyecek misiniz, toplu taşıma mı kullanacaksınız?','En hızlı mı en kolay yolu mu istersiniz?','Kontrol etmek için ilk yönlendirmeyi tekrar eder misiniz?','Başka bir konuda yardıma ihtiyacınız var mı?']},
    pron:{en:['How can I get to the city centre?','Should I turn left at the traffic lights?'],ru:['Как пройти в центр города?','На светофоре повернуть налево?'],uz:['Shahar markaziga qanday borsam bo‘ladi?','Svetofordan chapga burilaymi?'],tr:['Şehir merkezine nasıl gidebilirim?','Trafik ışıklarından sola mı dönmeliyim?']}},
  emergency:{icon:'🆘',title:'Acil durum',hint:'Yardım isteme ve temel bilgi verme',place:'Kamusal bir alanda acil yardım noktası',role:'Mira acil yardım görevlisi.',goal:'Güvenli biçimde yardım iste, konumu ve temel durumu açıkla.',turns:4,
    tasks:['Yardıma ihtiyacın olduğunu söyle','Konumu açıkla','Ne olduğunu kısa anlat','Sorulan iletişim bilgisini yanıtla'],
    phrases:{en:['I need help.','We are near …','Please call an ambulance.'],ru:['Мне нужна помощь.','Мы находимся рядом с …','Пожалуйста, вызовите скорую помощь.'],uz:['Menga yordam kerak.','Biz … yaqinidamiz','Iltimos, tez yordam chaqiring.'],tr:['Yardıma ihtiyacım var','… yakınındayız','Lütfen ambulans çağırın']},
    starters:{en:'Emergency assistance. Tell me first: are you in a safe place right now?',ru:'Служба экстренной помощи. Сначала скажите: вы сейчас в безопасном месте?',uz:'Favqulodda yordam. Avval ayting: hozir xavfsiz joydamisiz?',tr:'Acil yardım hattı. Önce söyleyin: Şu anda güvenli bir yerde misiniz?'},
    questions:{en:['Where exactly are you?','What happened? Please use one short sentence.','Does anyone need medical help?','What phone number can the responders use?'],ru:['Где именно вы находитесь?','Что случилось? Скажите одним коротким предложением.','Кому-нибудь нужна медицинская помощь?','По какому номеру с вами связаться?'],uz:['Aniq qayerdasiz?','Nima bo‘ldi? Bir qisqa gap bilan ayting.','Kimdir tibbiy yordamga muhtojmi?','Qutqaruvchilar qaysi telefon raqamiga qo‘ng‘iroq qilsin?'],tr:['Tam olarak neredesiniz?','Ne oldu? Tek kısa cümleyle anlatın.','Tıbbi yardıma ihtiyacı olan biri var mı?','Ekipler hangi telefon numarasından ulaşabilir?']},
    pron:{en:['I need help. We are near the station.','Please call an ambulance.'],ru:['Мне нужна помощь. Мы рядом с вокзалом.','Пожалуйста, вызовите скорую помощь.'],uz:['Menga yordam kerak. Biz vokzal yaqinidamiz.','Iltimos, tez yordam chaqiring.'],tr:['Yardıma ihtiyacım var. İstasyonun yakınındayız.','Lütfen ambulans çağırın.']}}
};

Object.keys(V5_SCENARIOS).forEach(key=>delete V5_SCENARIOS[key]);
Object.entries(WP83_SCENARIOS).forEach(([key,row])=>V5_SCENARIOS[key]={icon:row.icon,title:row.title,hint:row.hint});

function wp83Scenario(id=v5AiScenario){return WP83_SCENARIOS[id]||WP83_SCENARIOS.intro}
function wp83TargetText(map,fallback=''){return map?.[activeCourse]||map?.en||fallback}
function wp83EnsureRoot(){const root=v5Ensure();root.scenarioSessions=root.scenarioSessions&&typeof root.scenarioSessions==='object'?root.scenarioSessions:{};root.pronunciationMode=root.pronunciationMode||'word';return root}
function wp83SessionKey(){return `${activeCourse}:${v5AiScenario}`}
function wp83Session(){const root=wp83EnsureRoot(),key=wp83SessionKey(),scenario=wp83Scenario();let row=root.scenarioSessions[key];if(!row||row.schema!==WP83_SESSION_SCHEMA)row=root.scenarioSessions[key]={schema:WP83_SESSION_SCHEMA,startedAt:new Date().toISOString(),turns:0,completed:[],scores:[],lastScore:0};row.completed=Array.isArray(row.completed)?row.completed:[];row.scores=Array.isArray(row.scores)?row.scores:[];row.turns=Number(row.turns)||0;row.lastScore=Number(row.lastScore)||0;row.targetTurns=scenario.turns;return row}
function wp83ResetSession(){const root=wp83EnsureRoot();root.scenarioSessions[wp83SessionKey()]={schema:WP83_SESSION_SCHEMA,startedAt:new Date().toISOString(),turns:0,completed:[],scores:[],lastScore:0,targetTurns:wp83Scenario().turns};v5Save()}
function wp83Level(){return $('#wp65AiLevel')?.value||v5Ensure().preferences.aiLevel||'A1'}
function wp83TokenCount(text=''){return (String(text).match(/[\p{L}\p{N}]+/gu)||[]).length}
function wp83SmoothedScore(raw,previous=0){raw=Math.max(48,Math.min(98,Number(raw)||70));if(!previous)return Math.round(70+(raw-75)*.45);const delta=Math.max(-11,Math.min(11,raw-previous));return Math.round(previous+delta)}
function wp83RecordTurn(message,feedback){const session=wp83Session(),scenario=wp83Scenario();session.turns++;if(wp83TokenCount(message)>=2){const next=scenario.tasks.findIndex((_,index)=>!session.completed.includes(index));if(next>=0)session.completed.push(next)}const score=wp83SmoothedScore(feedback?.score||72,session.lastScore);session.lastScore=score;session.scores.push({score,grammar:Number(feedback?.metrics?.grammar)||score,clarity:Number(feedback?.metrics?.clarity)||score,fluency:Number(feedback?.metrics?.fluency)||score,at:new Date().toISOString()});session.scores=session.scores.slice(-40);if(feedback){feedback.rawScore=feedback.score;feedback.score=score;feedback.sessionTurn=session.turns}v5Save();return session}
function wp83Average(rows,key='score'){return rows.length?Math.round(rows.reduce((sum,row)=>sum+(Number(row[key])||0),0)/rows.length):0}
function wp83ScenarioQuestion(message,history){const scenario=wp83Scenario(),questions=wp83TargetText(scenario.questions,[]);const asked=(history||[]).filter(x=>x.role==='assistant').map(x=>String(x.text||'').toLocaleLowerCase());const available=questions.filter(q=>!asked.some(a=>a.includes(String(q).toLocaleLowerCase())||String(q).toLocaleLowerCase().includes(a)));const session=wp83Session();return available[Math.min(session.turns,Math.max(0,available.length-1))]||available[0]||questions[session.turns%Math.max(1,questions.length)]||'Could you tell me a little more?'}
function wp83Acknowledgement(){const lists={en:['Great, thank you.','That makes sense.','Good, I understand.','All right.'],ru:['Хорошо, спасибо.','Понятно.','Отлично, я понимаю.','Хорошо.'],uz:['Yaxshi, rahmat.','Tushunarli.','Ajoyib, tushundim.','Mayli.'],tr:['Harika, teşekkür ederim.','Anladım.','Güzel, devam edelim.','Tamam.']};const list=lists[activeCourse]||lists.en;return list[wp83Session().turns%list.length]}

v5ScenarioStarter=function(){return wp83TargetText(wp83Scenario().starters,'Hi! Let’s practise a real conversation.')};
wp80ContextQuestion=function(message,history){return wp83ScenarioQuestion(message,history)};
wp80Acknowledgement=function(){return wp83Acknowledgement()};

function wp83EnsureCoachShell(){
  const view=$('#view-ai');if(!view)return;
  const eye=view.querySelector('.section-title .eyebrow');if(eye)eye.textContent='CONVERSATION COACH 4.0';
  const title=view.querySelector('.section-title h1');if(title)title.textContent='Mira ile gerçek konuşma pratiği';
  const desc=view.querySelector('.section-title .muted');if(desc)desc.textContent='Günlük yaşam senaryosunu tamamla; Mira konuşmanı dinlesin, nazikçe düzeltsin ve oturum sonunda gelişim raporu versin.';
  const chat=$('.ai-chat-panel');if(chat&&!$('#wp83ScenarioBrief'))chat.querySelector('.ai-chat-head')?.insertAdjacentHTML('afterend',`<section id="wp83ScenarioBrief" class="wp83-scenario-brief"></section>`);
  const tools=$('.wp65-ai-head-tools');if(tools&&!$('#wp83FinishSession'))tools.insertAdjacentHTML('beforeend','<button id="wp83FinishSession" class="soft wp83-finish-session" type="button">Oturumu bitir</button>');
  const head=$('.ai-chat-head > div:first-child');if(head&&!head.querySelector('.wp83-mira-avatar'))head.insertAdjacentHTML('afterbegin','<span class="wp83-mira-avatar" aria-hidden="true">🤖</span>');
  const autoSpeak=$('#wp65AiAutoSpeak')?.closest('label');if(autoSpeak)autoSpeak.title='Cihazda uygun bir kadın sesi varsa Mira onu önceliklendirir.';
  const hero=$('#wp71ConversationSpotlight');if(hero){const h=hero.querySelector('h2'),d=hero.querySelector('[data-wp71="description"]');if(h)h.textContent='Conversation Coach 4.0 · Mira';if(d)d.textContent='10 gerçek yaşam senaryosu, görev ilerlemesi, nazik düzeltme ve oturum raporu.'}
  if(!$('#wp83SessionReport'))document.body.insertAdjacentHTML('beforeend',`<dialog id="wp83SessionReport" class="modal wp83-session-report"><button class="sheet-close" data-close="wp83SessionReport">×</button><div id="wp83SessionReportBody"></div></dialog>`);
}
function wp83RenderScenarioBrief(){
  const box=$('#wp83ScenarioBrief');if(!box)return;const scenario=wp83Scenario(),session=wp83Session(),completed=new Set(session.completed),phrases=wp83TargetText(scenario.phrases,[]),percent=Math.round(completed.size/Math.max(1,scenario.tasks.length)*100);
  box.innerHTML=`<div class="wp83-brief-top"><div><span class="wp83-scene-icon">${scenario.icon}</span><div><small>ROL OYUNU · ${esc(wp83Level())}</small><b>${esc(scenario.place)}</b><p>${esc(scenario.role)}</p></div></div><span class="wp83-turn-pill">${session.turns} cevap</span></div><div class="wp83-goal"><small>HEDEF</small><p>${esc(scenario.goal)}</p></div><div class="wp83-mission-progress"><div><span>Görev ilerlemesi</span><b>${completed.size} / ${scenario.tasks.length}</b></div><progress max="100" value="${percent}"></progress></div><div class="wp83-task-list">${scenario.tasks.map((task,index)=>`<span class="${completed.has(index)?'done':index===completed.size?'current':''}"><i>${completed.has(index)?'✓':index+1}</i>${esc(task)}</span>`).join('')}</div><details class="wp83-useful-phrases"><summary>Bu senaryoda kullanabileceğin ifadeler</summary><div>${phrases.map(x=>`<button type="button" data-wp83-use-phrase="${esc(x)}">${esc(x)}</button>`).join('')}</div></details>`;
}
function wp83PolishCoachMessages(){
  $$('#aiChatMessages .ai-message.assistant > span').forEach(node=>{node.textContent='🤖';node.title='Mira'});
  $$('#aiChatMessages .ai-message.user > span').forEach(node=>node.title='Sen');
  const backend=$('#aiBackendStatus');if(backend){const cloud=!!V5_SECURITY.aiEnabled;backend.className=`ai-backend-status ${cloud?'ready':'local'}`;backend.innerHTML=cloud?'<b>Coach 4.0 · Güvenli Bulut AI</b><small>Bağlama duyarlı konuşma, ayrıntılı düzeltme ve App Check koruması aktif.</small>':'<b>Coach 4.0 · Yerel senaryo modu</b><small>10 gerçek yaşam senaryosu çevrimdışı çalışır. Güvenli bulut AI otomatik denetlenir.</small>'}
  const current=wp83Scenario();if($('#aiScenarioTitle'))$('#aiScenarioTitle').textContent=current.title;if($('#aiScenarioHint'))$('#aiScenarioHint').textContent=current.hint;
  $$('#aiScenarioList [data-ai-scenario]').forEach(btn=>{const row=wp83Scenario(btn.dataset.aiScenario),session=wp83EnsureRoot().scenarioSessions?.[`${activeCourse}:${btn.dataset.aiScenario}`],title=btn.querySelector('b'),small=btn.querySelector('small');if(title)title.textContent=row.title;if(small)small.textContent=row.hint;let badge=btn.querySelector('.wp83-scenario-badge');if(!badge){badge=document.createElement('em');badge.className='wp83-scenario-badge';btn.appendChild(badge)}badge.textContent=session?.completed?.length>=row.tasks.length?'✓ Tamam':`${row.turns} adım`});
}
const wp83RenderAiBase=renderAiCoach;
renderAiCoach=function(){wp83RenderAiBase();wp83ApplyVersion();wp83EnsureCoachShell();wp83RenderScenarioBrief();wp83PolishCoachMessages()};

const wp83SendAiBase=v5SendAiMessage;
v5SendAiMessage=async function(message,options={}){const result=await wp83SendAiBase(message,options);const history=v5HistoryForScenario(),assistant=[...history].reverse().find(x=>x.role==='assistant'&&x.feedback);if(assistant?.feedback&&!assistant.feedback.wp83Recorded){wp83RecordTurn(message,assistant.feedback);assistant.feedback.wp83Recorded=true;v5Save()}renderAiCoach();return result};

const wp83VoiceName=/female|woman|zira|samantha|victoria|ava|aria|jenny|susan|karen|moira|tessa|veena|fiona|serena|hazel|shelley|libby|sonia|natasha|joanna|kendra|kimberly|salli|amy|emma|olivia|filiz|yelda/i;
const wp83PickVoiceBase=v5PickVoice;
v5PickVoice=function(lang=v5VoiceLang(),name=v5VoicePreference()){
  refreshSpeechVoices();if($('#view-ai')?.classList.contains('active')){const prefix=String(lang||'en').slice(0,2).toLowerCase(),candidates=speechVoices.filter(v=>String(v.lang||'').toLowerCase().startsWith(prefix));const preferred=candidates.find(v=>wp83VoiceName.test(v.name||''));if(preferred)return preferred}
  return wp83PickVoiceBase(lang,name);
};

function wp83FinishSession(){
  const scenario=wp83Scenario(),session=wp83Session(),rows=session.scores||[],completed=session.completed?.length||0,score=wp83Average(rows),grammar=wp83Average(rows,'grammar'),clarity=wp83Average(rows,'clarity'),fluency=wp83Average(rows,'fluency'),done=completed>=scenario.tasks.length;
  const body=$('#wp83SessionReportBody');if(!body)return;body.innerHTML=`<div class="wp83-report-hero"><span>${done?'🏆':'🧭'}</span><p class="eyebrow">CONVERSATION COACH 4.0</p><h2>${esc(scenario.title)} oturum raporu</h2><p>${done?'Senaryo görevlerini tamamladın.':'Oturumu burada bitirdin; kalan görevlerle daha sonra devam edebilirsin.'}</p></div><div class="wp83-report-score"><strong>${score||'—'}</strong><span>ortalama konuşma puanı</span></div><div class="wp83-report-metrics"><span><b>${grammar||'—'}</b><small>Dil bilgisi</small></span><span><b>${clarity||'—'}</b><small>Anlaşılırlık</small></span><span><b>${fluency||'—'}</b><small>Akıcılık</small></span><span><b>${session.turns}</b><small>Cevap</small></span></div><div class="wp83-report-tasks"><b>${completed} / ${scenario.tasks.length} görev tamamlandı</b>${scenario.tasks.map((task,index)=>`<p class="${session.completed.includes(index)?'done':''}">${session.completed.includes(index)?'✓':'○'} ${esc(task)}</p>`).join('')}</div><div class="wp83-report-actions"><button type="button" class="secondary" data-close="wp83SessionReport">Kapat</button><button id="wp83RestartScenario" type="button" class="primary">Senaryoyu yeniden başlat</button></div>`;$('#wp83SessionReport').showModal()}

function wp83PronunciationPhrases(){const scenario=wp83Scenario(),phrases=wp83TargetText(scenario.pron,[]);return phrases.length?phrases:['Could you say that again, please?']}
function wp83SentenceFromWord(word){const example=displayClean(String(word?.example||'').replace(/^•\s*/,''));if(example&&example.length<=120&&wp83TokenCount(example)>=3)return example;return word?.english||''}
function wp83SelectPronunciationTarget(){
  const root=wp83EnsureRoot();wp83PronunciationMode=root.pronunciationMode||wp83PronunciationMode;
  if(wp83PronunciationMode==='scenario'){const list=wp83PronunciationPhrases(),text=list[Math.floor(Math.random()*list.length)];v5PronunciationWord={id:`scenario-${v5AiScenario}-${Date.now()}`,english:text,pronunciation:'Senaryo cümlesi',meaningTr:wp83Scenario().title,level:wp83Level(),wp83Custom:true};}
  else{const candidates=words.filter(w=>w?.english&&!flagOf(w.id,'ignored')&&String(w.english).length<=60);const word=candidates[Math.floor(Math.random()*Math.max(1,candidates.length))]||words[0]||null;if(!word)return null;v5PronunciationWord=wp83PronunciationMode==='sentence'?{...word,english:wp83SentenceFromWord(word),pronunciation:`${word.pronunciation||''} · örnek cümle`,meaningTr:firstMeaning(word),wp83Custom:true}:word;}
  return v5PronunciationWord;
}
function wp83NewPronunciationTarget(){if(wp83SelectPronunciationTarget())renderPronunciationLab()}
v5RandomPronunciationTarget=wp83NewPronunciationTarget;

function wp83NormalizeTokens(text=''){return v5NormalizeSpeech(text).split(' ').filter(Boolean)}
function wp83Lcs(a,b){const dp=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)dp[i][j]=a[i-1]===b[j-1]?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1]);let i=a.length,j=b.length,matched=[];while(i&&j){if(a[i-1]===b[j-1]){matched.unshift(i-1);i--;j--}else if(dp[i-1][j]>=dp[i][j-1])i--;else j--}return matched}
function wp83PronunciationAnalysis(target,spoken,durationMs=0,confidence=0){
  const targetTokens=wp83NormalizeTokens(target),spokenTokens=wp83NormalizeTokens(spoken),matchedIndexes=wp83Lcs(targetTokens,spokenTokens),matchedSet=new Set(matchedIndexes),completeness=Math.round(matchedIndexes.length/Math.max(1,targetTokens.length)*100),accuracy=v5PronunciationScore(target,spoken),expected=Math.max(900,targetTokens.length/2.25*1000),ratio=durationMs?durationMs/expected:1,tempo=Math.max(45,Math.min(100,100-Math.abs(1-ratio)*42)),confScore=confidence>0?Math.round(confidence*100):Math.min(94,accuracy+4),fluency=Math.round(tempo*.65+confScore*.35),score=Math.round(accuracy*.52+completeness*.28+fluency*.20),missing=targetTokens.filter((_,index)=>!matchedSet.has(index)),extra=spokenTokens.filter(word=>!targetTokens.includes(word));
  return {score,accuracy,completeness,fluency,confidence:confScore,durationMs,missing,extra,targetTokens,matchedIndexes};
}
function wp83PronunciationAdvice(a){if(a.score>=88)return'Telaffuzun çok net. Aynı cümleyi biraz daha doğal ritimle tekrar edebilirsin.';if(a.completeness<75)return`Eksik veya algılanmayan bölüme odaklan: ${a.missing.slice(0,4).join(', ')||'cümleyi tamamla'}.`;if(a.accuracy<70)return'Kelimeleri daha yavaş ve heceleri birbirine karıştırmadan söyle.';if(a.fluency<70)return'Önce yavaş dinle, ardından cümleyi tek nefeste daha dengeli söyle.';return'İyi gidiyor. Bir tekrar daha yaparak sesi ve ritmi sabitle.'}
function wp83RenderPronResult(target,spoken,a){const result=$('#pronunciationResult');if(!result)return;const matched=new Set(a.matchedIndexes);result.hidden=false;result.className=`pronunciation-result wp83-pron-result ${a.score>=82?'good':a.score>=62?'mid':'low'}`;result.innerHTML=`<div class="wp83-pron-head"><strong>%${a.score}</strong><div><b>${a.score>=88?'Çok iyi!':a.score>=70?'İyi gidiyor':'Bir kez daha dene'}</b><p>${esc(wp83PronunciationAdvice(a))}</p></div></div><div class="wp83-pron-metrics"><span><b>${a.accuracy}</b><small>Doğruluk</small></span><span><b>${a.completeness}</b><small>Tamamlama</small></span><span><b>${a.fluency}</b><small>Akıcılık</small></span><span><b>${a.confidence}</b><small>Algılama</small></span></div><div class="wp83-word-analysis"><small>HEDEF KELİMELER</small><p>${a.targetTokens.map((word,index)=>`<mark class="${matched.has(index)?'hit':'miss'}">${esc(word)}</mark>`).join(' ')}</p></div><p class="wp83-heard"><small>Tarayıcının algıladığı:</small> ${esc(spoken||'—')}</p>`}

v5StartPronunciation=function(){
  const Ctor=wp65RecognitionCtor();if(!Ctor){toast('Bu tarayıcı canlı konuşma tanımayı desteklemiyor. Chrome veya Edge kullan.');return}
  if(v5Recognition){try{v5Recognition.abort()}catch{}}
  const btn=$('#pronunciationRecord'),result=$('#pronunciationResult'),target=v5TargetText();v5Recognition=new Ctor();v5Recognition.lang=v5VoiceLang();v5Recognition.interimResults=false;v5Recognition.maxAlternatives=5;v5Recognition.continuous=false;wp83PronunciationStartedAt=Date.now();wp83PronunciationConfidence=0;
  btn.classList.add('recording');btn.querySelector('b').textContent='Dinleniyor…';result.hidden=true;
  v5Recognition.onresult=event=>{const duration=Date.now()-wp83PronunciationStartedAt,candidates=[...event.results[0]].map(x=>({spoken:x.transcript,confidence:Number(x.confidence)||0})),ranked=candidates.map(x=>({...x,analysis:wp83PronunciationAnalysis(target,x.spoken,duration,x.confidence)})).sort((a,b)=>b.analysis.score-a.analysis.score),best=ranked[0]||{spoken:'',confidence:0,analysis:wp83PronunciationAnalysis(target,'',duration,0)},a=best.analysis;const root=wp83EnsureRoot();root.pronunciation.push({target,spoken:best.spoken,score:a.score,accuracy:a.accuracy,completeness:a.completeness,fluency:a.fluency,confidence:a.confidence,durationMs:duration,mode:wp83PronunciationMode,course:activeCourse,at:new Date().toISOString()});root.pronunciation=root.pronunciation.slice(-80);adjustPoints(a.score>=88?8:a.score>=70?5:2);v5Save();wp83RenderPronResult(target,best.spoken,a);renderPronunciationLab()};
  v5Recognition.onerror=event=>{toast(wp65MicMessage(event));};v5Recognition.onend=()=>{btn.classList.remove('recording');btn.querySelector('b').textContent='Okumaya başla'};try{v5Recognition.start()}catch{toast('Mikrofon şu an başlatılamadı.')}
};

function wp83EnsurePronunciationShell(){
  const panel=$('.voice-target-panel');if(!panel)return;
  if(!$('#wp83PronModes'))panel.querySelector('.voice-course-line')?.insertAdjacentHTML('afterend','<div id="wp83PronModes" class="wp83-pron-modes"><button type="button" data-wp83-pron-mode="word">Kelime</button><button type="button" data-wp83-pron-mode="sentence">Cümle</button><button type="button" data-wp83-pron-mode="scenario">Senaryo</button></div>');
  let note=$('#wp83VoiceAnalysisNote');if(!note){panel.insertAdjacentHTML('beforeend','<div id="wp83VoiceAnalysisNote" class="wp83-analysis-note"><span>◉</span><p><b>Temel ses analizi</b><br>Tarayıcının algıladığı metin, kelime tamamlama, süre ve tanıma güveni ölçülür. Fonem düzeyinde klinik ses analizi yapılmaz.</p></div>')}
  $$('#wp83PronModes button').forEach(btn=>btn.classList.toggle('active',btn.dataset.wp83PronMode===wp83PronunciationMode));
}
renderPronunciationLab=function(){
  if(!$('#view-pronunciation'))return;wp83PronunciationMode=wp83EnsureRoot().pronunciationMode||'word';if(!v5PronunciationWord)wp83SelectPronunciationTarget();const w=v5PronunciationWord;if(!w)return;const meta=COURSES[activeCourse];
  $('#voiceCourseFlag').innerHTML=typeof wp65FlagMarkup==='function'?wp65FlagMarkup(activeCourse):meta.flag;$('#voiceCourseName').textContent=meta.name;$('#pronunciationTarget').textContent=v5TargetText(w);$('#pronunciationTargetReading').textContent=w.pronunciation||'';$('#pronunciationTargetMeaning').textContent=v5TargetMeaning(w);$('#pronunciationTargetLevel').textContent=cefr(w)||wp83Level();
  const p=v5PronStats();$('#pronunciationCourseScore').textContent=p.count?`%${p.avg}`:'—';$('#pronunciationAttemptCount').textContent=`${p.count} deneme`;v5RenderVoiceSelect();wp83EnsurePronunciationShell();
  $('#pronunciationHistory').innerHTML=p.list.slice(-12).reverse().map(x=>`<article class="wp83-history-row"><span class="pron-score ${x.score>=82?'good':x.score>=62?'mid':'low'}">${x.score}</span><div><b>${esc(x.target)}</b><small>Algılanan: ${esc(x.spoken||'—')}</small>${x.accuracy?`<em>Doğruluk ${x.accuracy} · Tamamlama ${x.completeness} · Akıcılık ${x.fluency}</em>`:''}</div><time>${new Date(x.at).toLocaleDateString('tr-TR')}</time></article>`).join('')||'<p class="muted">Henüz telaffuz denemesi yok.</p>';
};

function wp83ApplyVersion(){
  document.documentElement.dataset.wpVersion=WP83_VERSION;const version=$('.version');if(version)version.textContent='v9.0.0 · Tester Beta';
  document.title='WordPilot 9.0.0 · Conversation Coach 4.0';
}

function setupV83Events(){
  document.addEventListener('click',event=>{
    const phrase=event.target.closest('[data-wp83-use-phrase]');if(phrase){const input=$('#aiChatInput');if(input){input.value=phrase.dataset.wp83UsePhrase;input.focus()}return}
    const mode=event.target.closest('[data-wp83-pron-mode]');if(mode){wp83PronunciationMode=mode.dataset.wp83PronMode;wp83EnsureRoot().pronunciationMode=wp83PronunciationMode;v5Save();wp83NewPronunciationTarget();return}
    if(event.target.closest('#wp83FinishSession')){wp83FinishSession();return}
    if(event.target.closest('#wp83RestartScenario')){wp83ResetSession();const key=`${activeCourse}:${v5AiScenario}`;v5Ensure().aiHistory[key]=[];v5Save();$('#wp83SessionReport')?.close();renderAiCoach();return}
    const scenario=event.target.closest('[data-ai-scenario]');if(scenario)setTimeout(()=>{wp83EnsureRoot();wp83RenderScenarioBrief()},0);
    if(event.target.closest('#aiResetChat'))setTimeout(()=>{wp83ResetSession();renderAiCoach()},0);
  },true);
  document.addEventListener('change',event=>{if(event.target.id==='wp65AiLevel')setTimeout(()=>{wp83RenderScenarioBrief();},0)},true);
}
function wp83AfterInit(){wp83ApplyVersion();wp83EnsureRoot();wp83PronunciationMode=wp83EnsureRoot().pronunciationMode||'word';wp83EnsureCoachShell();renderAiCoach();renderPronunciationLab()}
