/* WordPilot v9.2.0 — 5000 English cards, Phrase Lab and Reader coverage. */
const WP92_VERSION='9.2.0';
const WP92_COUNTS={en:5000,ru:1500,uz:1000,tr:1000,es:1000,de:1000,fr:1000,it:1000,pt:1000,ja:1000,ko:1000,zh:1000};
let wp92Phrases=[],wp92PhraseFilter={category:'',level:'',search:''};
function wp92Count(id){return Number(WP92_COUNTS[id]||1000)}
function wp92Text(id){if(id==='en')return '5000 İngilizce kelime · 1000 incelenmiş + 4000 beta';if(id==='ru')return '1500 kontrollü Rusça · 5000 kavram yol haritası';if(id==='uz')return '1000 kontrollü Özbekçe · 5000 kavram yol haritası';return `${wp92Count(id)} bağlantılı kayıt · 5000 kavram yol haritası`}
function wp92GroupOptions(){const g=$('#groupFilter');if(!g)return;const cur=g.value,max=wp92Count(activeCourse);let h=`<option value="">${max} kaydın tümü</option>`;if(activeCourse==='en')h+='<option value="base1000">1–1000 İncelenmiş Çekirdek</option><option value="extended2000">1001–3000 Genişletilmiş Beta</option><option value="advanced5000">3001–5000 İleri Düzey Beta</option>';else if(activeCourse==='ru')h+='<option value="wp91core">1–1000 Temel Rusça</option><option value="wp91extended">1001–1500 Genişletilmiş Rusça</option>';g.innerHTML=h;if([...g.options].some(o=>o.value===cur))g.value=cur}
const wp92FilteredBase=filteredWords;
filteredWords=function(){if(activeCourse==='en'&&$('#groupFilter')?.value==='advanced5000'){const s=($('#wordSearch')?.value||'').trim().toLocaleLowerCase('tr-TR'),l=$('#levelFilter')?.value||'',st=$('#statusFilter')?.value||'';let a=words.filter(w=>Number(w.id)>=3001&&Number(w.id)<=5000);if(s)a=a.filter(w=>[w.english,w.meaning,w.pronunciation,w.example,w.translation].some(v=>String(v||'').toLocaleLowerCase('tr-TR').includes(s)));if(l)a=a.filter(w=>cefr(w)===l);if(st)a=a.filter(w=>statusOf(w.id)===st);const r=typeof wp82LibraryRange!=='undefined'?wp82LibraryRange:{};if(Number.isFinite(r.start)&&Number.isFinite(r.end))a=a.filter(w=>Number(w.id)>=r.start&&Number(w.id)<=r.end);return a}return wp92FilteredBase()};
function wp92Normalize(raw){return String(raw||'').toLowerCase().replace(/[’']/g,"'").replace(/^[^a-zа-яё]+|[^a-zа-яё]+$/gi,'')}
const WP92_IRREGULAR={went:'go',gone:'go',going:'go',saw:'see',seen:'see',made:'make',took:'take',taken:'take',bought:'buy',brought:'bring',thought:'think',found:'find',knew:'know',known:'know',wrote:'write',written:'write',spoke:'speak',spoken:'speak',children:'child',men:'man',women:'woman',feet:'foot',teeth:'tooth',mice:'mouse',better:'good',best:'good',worse:'bad',worst:'bad',was:'be',were:'be',been:'be',did:'do',done:'do',had:'have',has:'have'};
function wp64Lookup(raw){const key=wp92Normalize(raw),list=activeCourse==='ru'?ruWords:words;if(!key)return null;const direct=list.find(w=>[w.english,w.word,w.stress].some(v=>wp92Normalize(v)===key));if(direct)return direct;const base=WP92_IRREGULAR[key];if(base){const row=list.find(w=>[w.english,w.word].some(v=>wp92Normalize(v)===base));if(row)return row}const tries=[];if(key.endsWith('ies'))tries.push(key.slice(0,-3)+'y');if(key.endsWith('es'))tries.push(key.slice(0,-2));if(key.endsWith('s'))tries.push(key.slice(0,-1));if(key.endsWith('ied'))tries.push(key.slice(0,-3)+'y');if(key.endsWith('ed'))tries.push(key.slice(0,-2),key.slice(0,-1));if(key.endsWith('ing'))tries.push(key.slice(0,-3),key.slice(0,-3)+'e');for(const t of tries){const row=list.find(w=>[w.english,w.word].some(v=>wp92Normalize(v)===t));if(row)return row}return null}
function wp64ShowWordPopup(btn){const raw=btn.dataset.wp64Word,row=wp64Lookup(raw),line=Number(btn.dataset.wp64Line),meaning=row?wp64Meaning(row):'Bağlam içinde yeni kelime · sözlük inceleme kuyruğunda',reading=row?wp64Reading(row):'',context=wp64ContextTranslation(line);wp64Ui.wordContext={raw,row,line,meaning,reading,context,storyId:v5Story?.id||''};const popup=$('#wp64WordPopup');popup.innerHTML=`<button type="button" class="wp64-popup-close" data-wp64-popup-close>×</button><p class="eyebrow">${row?'KELİME ANLAMI':'BAĞLAM KARTI'}</p><h3>${esc(row?.stress||row?.english||raw)}</h3>${reading?`<p class="wp64-reading">${esc(reading)}</p>`:''}<strong>${esc(meaning)}</strong>${context?`<small><b>Bağlam:</b> ${esc(context)}</small>`:''}<div><button type="button" class="secondary" data-wp64-word-speak>🔊 Dinle</button><button type="button" class="primary" data-wp64-save-word>＋ Kelimelerime ekle</button></div>`;popup.hidden=false;const r=btn.getBoundingClientRect(),pw=Math.min(360,window.innerWidth-24);popup.style.width=`${pw}px`;popup.style.left=`${Math.max(12,Math.min(window.innerWidth-pw-12,r.left+r.width/2-pw/2))}px`;popup.style.top=`${Math.min(window.innerHeight-popup.offsetHeight-12,r.bottom+8)}px`}
function wp92EnsurePhraseDialog(){if($('#wp92PhraseDialog'))return;document.body.insertAdjacentHTML('beforeend',`<dialog id="wp92PhraseDialog" class="modal wp92-phrase-dialog"><button class="sheet-close" data-wp92-close>×</button><p class="eyebrow">KALIPLAR & DOĞAL İNGİLİZCE</p><h2>Phrase Lab</h2><p>Konuşma kalıpları, kolokasyonlar, phrasal verbs ve deyimler.</p><div class="wp92-phrase-tools"><input id="wp92PhraseSearch" placeholder="Kalıp veya Türkçe anlam ara..."><select id="wp92PhraseCategory"><option value="">Tüm türler</option><option value="conversation">Konuşma</option><option value="collocation">Kolokasyon</option><option value="phrasal_verb">Phrasal verb</option><option value="idiom">Deyim</option></select><select id="wp92PhraseLevel"><option value="">Tüm seviyeler</option><option>A2</option><option>B1</option><option>B2</option></select></div><div id="wp92PhraseStats"></div><div id="wp92PhraseList" class="wp92-phrase-list"></div></dialog>`)}
async function wp92OpenPhraseLab(){wp92EnsurePhraseDialog();if(!wp92Phrases.length){try{wp92Phrases=await fetch('phrases_v92.json?v=9.2.0',{cache:'no-store'}).then(r=>r.json())}catch(e){toast('Kalıp verisi açılamadı.');return}}wp92RenderPhrases();$('#wp92PhraseDialog').showModal()}
function wp92RenderPhrases(){const q=(wp92PhraseFilter.search||'').toLocaleLowerCase('tr-TR');let a=wp92Phrases.filter(x=>(!wp92PhraseFilter.category||x.category===wp92PhraseFilter.category)&&(!wp92PhraseFilter.level||x.cefr===wp92PhraseFilter.level)&&(!q||[x.phrase,x.meaningTr,x.example,x.translation].some(v=>String(v).toLocaleLowerCase('tr-TR').includes(q))));$('#wp92PhraseStats').textContent=`${a.length} kalıp gösteriliyor`;$('#wp92PhraseList').innerHTML=a.map(x=>`<article><div><span>${x.cefr} · ${x.category.replace('_',' ')}</span><h3>${esc(x.phrase)}</h3><b>${esc(x.meaningTr)}</b><p>${esc(x.example)}</p><small>${esc(x.translation)}</small></div><button type="button" data-wp92-speak="${esc(x.phrase)}">🔊</button></article>`).join('')||'<div class="story-empty"><h3>Bu filtrede kalıp yok.</h3></div>'}
function wp92Apply(){document.documentElement.dataset.wpVersion=WP92_VERSION;document.title='WordPilot 9.5 · Conversation Coach Pro · Reader 3.0';wp91Set($('.version'),'v9.5.0 · Conversation Coach Pro');Object.keys(COURSES).forEach(id=>{COURSES[id].displayCount=wp92Count(id);COURSES[id].actualCount=wp92Count(id)});$$('.course-card[data-course]').forEach(c=>wp91Set(c.querySelector('small'),wp92Text(c.dataset.course)));wp91Set($('#activeCourseSummary'),`${COURSES[activeCourse]?.name||activeCourse} · ${wp92Text(activeCourse)}`);wp92GroupOptions();const max=Math.max(1,words.length||wp92Count(activeCourse));['setupStart','setupEnd','wp82RangeStart','wp82RangeEnd'].forEach(id=>{const i=$('#'+id);if(i)i.max=String(max)});wp91Set($('#wp82RangeMax'),`1–${max} arasından istediğin kayıtları doğrudan aç.`);const p=$('#wp90CoveragePanel');if(p)p.innerHTML=`<div><p class="eyebrow">V9.2 İÇERİK DURUMU</p><b>${activeCourse==='en'?'5000 gerçek İngilizce kelime':wp92Count(activeCourse)+' gerçek kayıt'}</b><small>${activeCourse==='en'?'1000 incelenmiş çekirdek + 4000 beta; yeni 3001–5000 katmanı editör kontrolü bekler.':'Olmayan çeviriler hazır gibi gösterilmez; 5000 kavram yol haritasında eksik olarak işaretlenir.'}</small></div><div class="wp90-coverage-stats"><span><b>${max}</b><small>aktif kayıt</small></span><span><b>${v5Stories?.filter(s=>s.course===activeCourse).length||0}</b><small>hikâye</small></span><span><b>120</b><small>doğal kalıp</small></span></div>`;const pc=$('.collection-card[data-collection="phrases"]');if(pc){pc.hidden=false;wp91Set(pc.querySelector('b'),'Kalıplar & Doğal İngilizce');wp91Set(pc.querySelector('small'),'120 konuşma kalıbı, kolokasyon, phrasal verb ve deyim')}const storyCard=$('[data-v5-open="stories"] small');if(storyCard)wp91Set(storyCard,`A1–C2 · ${v5Stories?.filter(s=>s.course===activeCourse).length||0} metin · dokunmatik sözlük`)}
function setupV92Events(){document.addEventListener('click',e=>{const phrases=e.target.closest('.collection-card[data-collection="phrases"]');if(phrases){e.preventDefault();e.stopImmediatePropagation();wp92OpenPhraseLab();return}if(e.target.closest('[data-wp92-close]')){$('#wp92PhraseDialog')?.close();return}const sp=e.target.closest('[data-wp92-speak]');if(sp){speak(sp.dataset.wp92Speak,'en-US');return}},true);document.addEventListener('input',e=>{if(e.target?.id==='wp92PhraseSearch'){wp92PhraseFilter.search=e.target.value;wp92RenderPhrases()}},true);document.addEventListener('change',e=>{if(e.target?.id==='wp92PhraseCategory'){wp92PhraseFilter.category=e.target.value;wp92RenderPhrases()}if(e.target?.id==='wp92PhraseLevel'){wp92PhraseFilter.level=e.target.value;wp92RenderPhrases()}},true)}
function wp92AfterInit(){if(typeof wp90ApplyVersionLock==='function')wp90ApplyVersionLock=wp92Apply;wp92Apply();/* v9.5: eski sürüm gözlemcisi devre dışı */}
